### ISSUE TITLE
Abrir el código fuente

### ISSUE THREAD

**Issue by midudev** [midudev/adventjs-issues#1]
¡Hola! 👋 

Como ves, no hay código para https://adventjs.dev. ¡Es normal! El código está hecho un desastre y ahora mismo no voy a aceptar PRs ni contribuciones...

Tengo que pulir unas cuantas cosas antes de hacerlo disponible. Pero eventualmente, intentaré que esté disponible para todo el mundo.

¡Gracias por la comprensión y disfruta de AdventJS!

**Comment by erasmoh** [comment]
Me ofrezco con el responsive, venía a eso. Avisa en lo que lo liberes :)

**Comment by TeoDiaz** [comment]
Me suscribo, una vez abierto infórmanos 😉 Gracias

**Comment by midudev** [comment]
Al final no vamos a abrir el código fuente del proyecto.
