### ISSUE TITLE
Añadir ranking

### ISSUE THREAD

**Issue by chsanch** [midudev/adventjs-issues#10]
Para saber quien ha completado cada reto, e incluso ver las soluciones que han subido

**Comment by Llambi** [comment]
Además de un ranking podría haber un apartado de stats para ver cuánta gente a ido solucionando cada reto y ver la evolución de calendario de adviento.

**Comment by Jibaru** [comment]
También sería bueno añadir un cronómetro visible

**Comment by palawer** [comment]
> Además de un ranking podría haber un apartado de stats para ver cuánta gente a ido solucionando cada reto y ver la evolución de calendario de adviento.

Sí, un ranking anónimo mostrando cuanta gente ha completado los retos... Algo así:

15 ░░░░░░░░░░ 200
14 ░░░░░░░░░░░ 230
13 ░░░░░░░░░░░░░░ 295
12 ░░░░░░░░░░░░░░░ 300
11 ░░░░░░░░░░░░░░░░░░░░░░ 497
10 ░░░░░░░░░░░░░░░░░░░░░░ 500
09 ░░░░░░░░░░░░░░░░░░░░░░ 506
08 ░░░░░░░░░░░░░░░░░░░░░░░ 800
07 ░░░░░░░░░░░░░░░░░░░░░░░░░ 1000
06 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1500
05 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1600
04 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1700
03 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1756
02 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2800
01 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░  2956

**Comment by palawer** [comment]
Aquí un script para ver el ranking:
https://github.com/palawer/adventjs/blob/master/get_stats.py
