### ISSUE TITLE
bug(ui): Contador de usuarios que han enviado solución

### ISSUE THREAD

**Issue by davorpa** [midudev/adventjs-issues#100]
Tras el primer envío válido, el contador de usuarios se sigue incrementando si se hacen modificaciones o se entra de nuevo y se vuelve a enviar el código.

Sin embargo, si se refresca la página aparece el valor inicial (supongo que el correcto ya que se cuentan usuarios y no soluciones)

**Comment by xavikortes** [comment]
Duplicado #99

**Comment by davorpa** [comment]
> Duplicado #99

No me había dado cuenta. Creo que lo escribimos  al mismo tiempo.

Sigo ese hilo.
