### ISSUE TITLE
pruebas unitarias : reto 6

### ISSUE THREAD

**Issue by NicolasNinoViancha** [midudev/adventjs-issues#101]
Revisar los test automáticos para la prueba 6.
Realizando el codigo correspondiente al desafio, el siguiente codigo pasara : 

const sumPairs = (numbers = [], result = 0) => {
    let resultsMatrix = [];
    let limit = numbers.length;
    for (let i = 0; i < limit; i++) {
        let sumA = numbers[i];
        for (let j = i + 1; j < limit; j++) {
            let sumB = numbers[j];
            let verify = sumA + sumB === result;
            if (verify) {
                let limitMatrix = resultsMatrix.length;
                let verifyPair = sumB % 2 === 0;
                resultsMatrix[limitMatrix] = [sumA, sumB];
                if (verifyPair) {
                    i = limit;
                    j = limit;
                }
            }
        }
    }
    let resultVector = resultsMatrix.length > 0 ? resultsMatrix[0] : null;
    return resultVector;
}
sin embargo, de acuerdo a las especificaciones dadas para el reto, para el siguiente caso de prueba :
sumPairs([7, 1, 6, 2], 8) , la respuesta debería ser [6,2]
Al existir multiples combinaciones de sumandos que cumplen con la condicion de resultado, y ser este la unica pareja, cuyo segundo miembro es par. Sin embargo ejecutando el codigo anterior el resultado sera [7, 1], que corresponde a la primera pareja en cumplir la condicion.
El codigo correcto deberia ser : 
const sumPairs = (numbers = [], result = 0) => {
    let resultsMatrix = [];
    let limit = numbers.length;
    for (let i = 0; i < limit; i++) {
        let sumA = numbers[i];
        for (let j = i + 1; j < limit; j++) {
            let sumB = numbers[j];
            let verify = sumA + sumB === result;
            if (verify) {
                let limitMatrix = resultsMatrix.length;
                let verifyPair = sumB % 2 === 0;
                resultsMatrix[limitMatrix] = [sumA, sumB];
                if (verifyPair) {
                    i = limit;
                    j = limit;
                }
            }
        }
    }
    let resultVector = resultsMatrix.length > 0 ? resultsMatrix[resultsMatrix.length - 1] : null;
    return resultVector;
}
pero este debuelve el mensaje de consola : ¿Sabes que el 0 también existe, verdad? 😝

**Comment by davorpa** [comment]
> Al existir multiples combinaciones de sumandos que cumplen con la condicion de resultado, y ser este la unica pareja, cuyo segundo miembro es par. Sin embargo ejecutando el codigo anterior el resultado sera [7, 1], que corresponde a la primera pareja en cumplir la condicion.

Creo que has malinterpretado mal el enunciado.

En ningún sitio se dice que los números tengan que ser par/impar.

> La función debe devolver los dos valores del Array que sumen el resultado esperado. Como a veces pueden haber más de dos valores que sumen, **se devolverá el primero empezando por la izquierda que encuentre otro par**, sin importar lo lejos que esté a la derecha.

par = pareja, sin importar la distancia entre elementos.

Aquí una matrix más exhaustiva (assertions with [`chai`](https://www.chaijs.com/api/bdd/#method_eql):

```js
describe("Fixed tests", () =>
  for (const [nums, n, pair, message] of [
        [void 0, 1111, null],
        [NaN, NaN, null],
        [[NaN], NaN, null],
        [[NaN, NaN], NaN, [NaN, NaN], "NaN exists too"],
        [[], 10, null],
        [[10], 10, null],
        [[10], 8, null],
        [[0, 0], 0, [0, 0], "Zero exist too"],
        [[1, 1], 2, [1, 1]],
        [[1, 1], 3, null],
        [[-1, 1], 0, [-1, 1]],
        [[-15, 5, -15], -10, [-15, 5]],
        [[-15, -15, 5], -10, [-15, 5]],
        [[-15, 5, 7, -15], -10, [-15, 5]],
        [[-15, 3, -15, 5, -13], -10, [-15, 5]],
        [[5, -15], -10, [5, -15]],
        [[3, 5, 7, 2], 10, [3, 7]],
        [[-3, -2, 7, -5], 10, null],
        [[2, 2, 3, 1], 4, [2, 2]],
        [[6, 7, 1, 2], 8, [6, 2]],
        [[7, 1, 6, 2], 8, [7, 1]],
        [[7, 3, 6, 2], 9, [7, 1]],
        [[0, 2, 2, 3, -1, 1, 5], 6, [1, 5]],
      ]) {
    it(`sumPairs(${str(nums)}, ${n}) === ${str(pair)}`, () => {
      expect(sumPairs(nums, n)).to.be.deep.eql(pair), message);
    });
  }
});

function str(x, {max = 33}={}) {
  if (Array.isArray(x)) return "[" + (x.length > max ? x.slice(0, max) + ", ...+NN others".replace("NN", x.length - max) : x) + "]";
  return "" + x;
}
```

**Comment by fom78** [comment]
es suma de pares que den como resultado lo que se pide
