### ISSUE TITLE
No logro iniciar sesion con gitHub 

### ISSUE THREAD

**Issue by 77victordavid** [midudev/adventjs-issues#102]
Cuando intento iniciar sesion con github deja spinner y en la consola sale este error:
Uncaught (in promise) Error: Magic Extension Error (oauth): [server_error] Failed to generate temporary magic credential.
    at St.createError (_app-0fbcd05cc3c6948f.js:1)
    at _app-0fbcd05cc3c6948f.js:1

**Comment by midudev** [comment]
¿Me puedes decir qué navegador y sistema operativo usas? ¡Gracias!
