### ISSUE TITLE
Preguntas que deje en linkedin

### ISSUE THREAD

**Issue by fom78** [midudev/adventjs-issues#103]
Muy buena iniciativa!!! Enorme !!! Si es posible este mortal te va a pedir/preguntar unas cositas sobre el proyecto.

Veo que va de maravilla, el back en donde lo tenes alojado ? heroku, aws ? que plan usa ? Es como para tener una referencia para cuando tenga algo potable que meter en la red. XD

La DB mongo ?

Y me interesaria si es posible saber el tema de la autenticacion con github, en mi caso lo quiero hacer con gmail, y guardar ese usuario en mongo, es algo assi como lo realizaste ?

Y por ultimo, ojala subas el codigo mas adelante a github, se aprende mucho viendo tus videos y ni hablar mirando el codigo de un proyecto terminado y funcionando, desplegado completito!

Gracias por todo, sos un gran crack!!

**Comment by itsjuancho** [comment]
La mayoría de cosas las ha hablado en Twitch. En especial este >>> https://www.twitch.tv/videos/1221183073

Lo del OAuth está con Magic Link por lo que pude notar. Dentro de sus providers está Google > https://magic.link/docs/login-methods/social-logins/social-providers/google--gmail

Sin embargo, este tipo de dudas no van aquí. Mejor déjalas por [discord](https://discord.gg/midudev).

**Comment by midudev** [comment]
Cierro esto porque @itsjuancho ya ha contestado! :)
