### ISSUE TITLE
Hastag por ejercicio

### ISSUE THREAD

**Issue by anbillin** [midudev/adventjs-issues#104]
Sería interesante que hubiera un hastag por ejercicio para unificar las respuestas en las redes sociales. Quizás un `#adventjs{num}` o algo así.

**Comment by midudev** [comment]
Aunque la idea es interesante, lo dejo mejor a criterio de la gente. Con el hashtag #AdventJS a mi ya me vale. Quizás el año que viene lo tengo en cuenta desde el principio, para cuando se comparta el tweet para la edición 2022. :)
