### ISSUE TITLE
Nuestras respuestas

### ISSUE THREAD

**Issue by AntonioSantanaCorp** [midudev/adventjs-issues#106]
Las respuestas se guardan en angun lado, podemos acceder a nuestras soluciones?

**Comment by xavikortes** [comment]
Puedes acceder a tus propias soluciones cuando abres un reto de nuevo. Debería cargarse automáticamente tras un par de segundos

**Comment by midudev** [comment]
Se guardan si has iniciado sesión, las completas y le das a "Enviar solución".
