### ISSUE TITLE
Actualización de entregas en reto

### ISSUE THREAD

**Issue by Curbe8** [midudev/adventjs-issues#107]
Una ves que se genera una solución para un reto dado, al volver a ingresar se carga nuestra solución correctamente y sin problemas, pero el botón de "**Enviar solución**" sigue estando activado para realizar la entrega, al presionar el botón, el contador de usuarios que han entregado el reto se incrementa (cuando realmente no es así), al refrescar la página, el contador vuelve a estar en el número anterior ya que el usuario ya había entregado el reto.

**Comment by xavikortes** [comment]
Duplicado #99
