### ISSUE TITLE
Reto #3

### ISSUE THREAD

**Issue by ApoAdrian** [midudev/adventjs-issues#108]
Buenas. Estoy intentando el reto #3 El Grinch quiere fastidiar la Navidad

Creo que tengo el código correcto pero se queda `Ejecutando tests...` De forma infinita...

Es una llamada recursiva, pero lo he probado en local y me funciona...

```javascript
export default function isValid(letter) {
  if (!letter || letter.length === 0) {
    return false
  }
  const startIndex = letter.indexOf('(')
  if (startIndex >= 0) {
    const endIndex = letter.lastIndexOf(')')
    if (endIndex < 0) {
      return false
    }
    const subLetter = letter.substring(startIndex + 1, endIndex)
    if (subLetter.includes('{') || subLetter.includes('[')) {
      return false
    }
    return isValid(subLetter)
  }
  return true
}
```

**Comment by xavikortes** [comment]
Es posible que haya casos de tests (no expuestos en la plataforma) en los que tu llamada se queda colgado. Por eso solo funciona en local. Revisa que todo sea acorde al enunciado y no a los tests

**Comment by ApoAdrian** [comment]
El principal problema era que  `)(` hacía que el indice final fuera mayor que el inicial y el loop infinito. Pero revisando el código veo todo el desastre que es... 😂
