### ISSUE TITLE
No reconoce mi solución a pesar que según mis pruebas esta OK #Reto5 #DiferenciaEntreFechas

### ISSUE THREAD

**Issue by dadadev88** [midudev/adventjs-issues#109]
Saludos comunidad JS,

Estoy teniendo problemas con el reto N° 5 el cual solicita calcular la diferencia entre fechas en número de días (positivos o negativos) tomando como punto de partida el 25/12/2021 (Dec 25, 2021). El tema es que me está arrojando el error **_Yo diria que del 23 de diciembre al 25 hay 2 días_**, según mis pruebas está devolviendo los 2 días, adicional a ello he hecho otras pruebas con diferentes fecha y según mi criterio funciona ¿Algo se me está escapando?

Mi solución fue la siguiente:
```
/**
 * @param {Date} date date to diff
 */
export default function daysToXmas(date) {
  // 1 dia = 86400000ms
  const dateEnd = new Date('Dec 25, 2021');
  const diffDays = (dateEnd.getTime() - date.getTime()) / 86400000;

  return parseInt(diffDays);
}
```
![image](https://user-images.githubusercontent.com/26575279/145688121-64481ebe-8ec9-4343-af0d-0178e8591f58.png)

**Comment by davorpa** [comment]
Falta algún tipo de redondeo. A saber...
- Math.trunc
- Math.floor
- Math.ceil
- Math.round

**Comment by midudev** [comment]
Efectivamente, te falta un redondeo.
