### ISSUE TITLE
Algunos tests fallaron! (Sugerencias para tests)

### ISSUE THREAD

**Issue by Cedgo1997** [midudev/adventjs-issues#11]
Hola!!
Sería ideal que la plataforma te dijera qué tests fallan. 
Me sucede que completo un reto, lo pruebo en consola y efectivamente funciona, arroja los resultados deseados. Pero cuando coloco la función en el editor de adventJS, me surge el error de que ha fallado en algunos tests, pero no me dice cuáles. Claro, también puede que el ejercicio esté incorrecto, pero dado que no tengo ni idea de qué es lo que está incorrecto no puedo saber qué corregir. Saludos!! Está quedando genial ese proyecto, le daré seguimiento!
![image](https://user-images.githubusercontent.com/30558520/144303013-f9d0a498-6af5-4884-9667-ba9d2a5a7ccc.png)

**Comment by renatomendozac** [comment]
> Hola!! Sería ideal que la plataforma te dijera qué tests fallan. Me sucede que completo un reto, lo pruebo en consola y efectivamente funciona, arroja los resultados deseados. Pero cuando coloco la función en el editor de adventJS, me surge el error de que ha fallado en algunos tests, pero no me dice cuáles. Claro, también puede que el ejercicio esté incorrecto, pero dado que no tengo ni idea de qué es lo que está incorrecto no puedo saber qué corregir. Saludos!! Está quedando genial ese proyecto, le daré seguimiento! ![image](https://user-images.githubusercontent.com/30558520/144303013-f9d0a498-6af5-4884-9667-ba9d2a5a7ccc.png)

Lee bien el ejercicio amigo @Cedgo1997

**Comment by Cedgo1997** [comment]
@renatomendozac Es indiferente. Repito, incluso si la respuesta está mal (o haya una mala implementación de mi parte), **no sé qué tests fallaron**, esa es mi sugerencia, que te digan los tests que fallaron. Porque a veces uno es ciego. Igual lo solucioné cambiando un || por &&, pero el punto es que "no lo sabía al momento".

**Comment by renatomendozac** [comment]
@Cedgo1997 ahh ya entiendo, pero si los tests son visibles pierde sentido porque ya uno podría subir un código con puros if para cada que pase cada test.
Lo que se podría hacer es:
- Tener tests publicos y tener otros tests ocultos.
- Agregar un botón para correr los tests ocultos.

Plus: Agregar un scoreboard donde se ordenen por numero de intentos. (El numero de intento va incrementando por cada click al botón de correr test ocultos).

**Comment by trv469** [comment]
![image](https://user-images.githubusercontent.com/24488771/144327189-d0d1b27e-c24a-4bea-b0a6-99dd1cd78f7f.png)

Debería mostrarse el test también, para ver que casos esta considerando, tengo el mismo resultado pero por alguna razón me indica que en algo se esta fallando. 
 :)

**Comment by ZajithCorro** [comment]
> ![image](https://user-images.githubusercontent.com/24488771/144327189-d0d1b27e-c24a-4bea-b0a6-99dd1cd78f7f.png)
> 
> Debería mostrarse el test también, para ver que casos esta considerando, tengo el mismo resultado pero por alguna razón me indica que en algo se esta fallando. :)

El test te esta fallando porque el problema dice que tiene que contener la letra **n** y la letra **a** en la misma cadena. Además que no estas diferenciando entre si es **A** o **a** y **N** o **n** 🤔 😄

**Comment by midudev** [comment]
He hecho que los tests den más contexto sobre qué está fallando pero no vamos a mostrar la implementación de los tests. :)
