### ISSUE TITLE
Alertar al usuario antes de cambiar de página

### ISSUE THREAD

**Issue by Xotl** [midudev/adventjs-issues#110]
Van varias veces que me equivoco de botón y la página se regresa, por ejemplo si no tengo el foco en el área de texto y presiono la tecla de borrar. He hecho más de una vez varios de los ejercicios por eso, es frustrante.

Esto se solucionaría si antes de cambiar de página [se mostrara una alerta al usuario](https://stackoverflow.com/a/28627881/4687318) de que está navegando a otro lado.

**Comment by davorpa** [comment]
De ser cierto... Creo que mejor habría que mirar porqué estando en un campo de texto y dando a retroceder hace un `history.back`. **No es el comportamiento por defecto de los formularios**

**Comment by midudev** [comment]
> De ser cierto... Creo que mejor habría que mirar porqué estando en un campo de texto y dando a retroceder hace un `history.back`. **No es el comportamiento por defecto de los formularios**

Lo que comenta es que no está en el área de texto y le da atrás sin querer. :D

**Comment by Xotl** [comment]
> > De ser cierto... Creo que mejor habría que mirar porqué estando en un campo de texto y dando a retroceder hace un `history.back`. **No es el comportamiento por defecto de los formularios**
> 
> Lo que comenta es que no está en el área de texto y le da atrás sin querer. :D

Exacto... el escenario que @davorpa describe nunca me ha pasado. Así que no hay ningún misterio que resolver, sólo soy muy torpe, incluso ayer me pasó que accidentalmente presioné el botón de "Atrás" de mi mouse (los que están a los costados) y tuve que volver a empezar. 😣

**Comment by midudev** [comment]
Lo que vamos a hacer es guardar el código en el localStorage, de forma que aunque vayas atrás, no pierdas tu contenido. :) Más fácil y dos pájaros de un tiro.
