### ISSUE TITLE
Errores varios en el enunciado del día 12

### ISSUE THREAD

**Issue by albertobastos** [midudev/adventjs-issues#111]
El código de muestra nombra a la función `getMinJump`, pero en los ejemplos finales se llama a `avoidObstacles`.

El ejemplo de salida para `getMinJump([3, 7, 5])` no es correcto. Dice que la salida correcta es `3` (¡se caería en el obstáculo de la posición 3!) pero el resultado correcto es `2`.

**Comment by midudev** [comment]
Arreglados!
