### ISSUE TITLE
expresion regular no me funciona

### ISSUE THREAD

**Issue by sandybierhoff** [midudev/adventjs-issues#112]
Hola buenas noches....

Porque no funciona esta expresion regular ??

export default function isValid(letter) {
 var reg = /\([\w\säÄëËïÏöÖüÜáéíóúáéíóúÁÉÍÓÚÂÊÎÔÛâêîôûàèìòùÀÈÌÒÙ]+\)/;
 var matches = reg.exec(letter);
 return matches != null
}

Lo eh probado en local con todas las letras y funciona perfecto
donde me estoy equivocando ??

**Comment by midudev** [comment]
No te funciona porque está mal. La siguiente carta NO es válida. De hecho los tests te lo dicen.

![CleanShot 2021-12-13 at 12 14 09@2x](https://user-images.githubusercontent.com/1561955/145802616-aed8130e-7d02-49f8-b791-a0b73404c498.png)

A revisar el código.

**Comment by sandybierhoff** [comment]
Hola, disculpa, pero sigo sin entender por que me da false con ese mismo criterio que me pones..
https://jsfiddle.net/e2vcLzdq/

**Comment by sandybierhoff** [comment]
Es que no se por que no puse el \ antes del cierre del parentesis, que cosas.... jajaja mis disculpas..
