### ISSUE TITLE
Link roto cuando quieres avanzar a un día que aun no existe

### ISSUE THREAD

**Issue by arialdev** [midudev/adventjs-issues#114]
Cuando completas un reto aparece un modal con las posibilidades de compartir en RRSS el problema o pasar al del siguiente día.
Si el del siguiente día aun no ha sido publicado, el enlace queda roto.
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/48073509/145910478-0ec1887d-5aa0-4717-a45c-0de9331c4a54.png">
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/48073509/145910546-08433b0d-10cf-44fb-a1a8-5e187afd18d0.png">

**Comment by midudev** [comment]
Ya está solucionado!
<img width="1018" alt="CleanShot 2021-12-14 at 19 09 49@2x" src="https://user-images.githubusercontent.com/1561955/146055507-0101dfcd-3645-42a4-a65c-2372451a1e59.png">
