### ISSUE TITLE
La solucion del primer reto no quedo guardada

### ISSUE THREAD

**Issue by Juanse036** [midudev/adventjs-issues#117]
todas la soluciones que realicé me cargan menos la del primer reto,

**Comment by ezebinker** [comment]
A mí me pasó lo mismo, asumo que tiene que ver con que la desarrollamos ambos previo al guardado de las soluciones. 
Recién la armé de nuevo, no podía ver que no esté completa 🤣

**Comment by Juanse036** [comment]
Si debe ser, el problema es que también la armé de nuevo y me sigue sin guardar.. 😭
