### ISSUE TITLE
Quitar compilación en cada tecleo

### ISSUE THREAD

**Issue by beenjii14** [midudev/adventjs-issues#12]
Estaría bueno que no se compile el código cada que se teclea y que haya un botón para ejecutar las pruebas.

**Comment by ClaudioDuran** [comment]
O en su defecto, mover la etiqueta ya que molesta al desarrrollar.

**Comment by midudev** [comment]
Hola! No vamos a poner un botón para ejecutar las pruebas pero he movido los tests debajo del editor para que no molesten.
