### ISSUE TITLE
#17 no logro que pase los tests. 

### ISSUE THREAD

**Issue by mtofani** [midudev/adventjs-issues#126]
Chicos que tal, estoy con un problema de validación de los test. entiendo que la lógica esta funcionando segun lo esperando, tengo el mismo output que los ejemplos. 

[17.zip](https://github.com/midudev/adventjs-issues/files/7741383/17.zip)
<img width="530" alt="17 output" src="https://user-images.githubusercontent.com/69044164/146687445-4e61220b-21a9-4b88-9877-c77d74c05212.png">

**Comment by midudev** [comment]
Eso seguramente te pasa porque tienes dos funciones en lugar de tener sólo una.

Tener más de una función no es soportado en navegadores como Firefox.

Te recomiendo que te limites a tener una sola función y probar.

**Comment by mtofani** [comment]
Gracias! Veo de reescribirlo midu. Saludos
