### ISSUE TITLE
18 Error con duplicados

### ISSUE THREAD

**Issue by mtofani** [midudev/adventjs-issues#127]
Midu y comunidad! estoy atascado con el error "No estás gestionando bien los nombres duplicados... ¡Revísalo!"

Adjunto el codigo y el output,

Gracias!!
[18.zip](https://github.com/midudev/adventjs-issues/files/7741758/18.zip)

**Comment by midudev** [comment]
Estas cosas mejor en el canal de Discord en #adventjs.
