### ISSUE TITLE
Reto #03: El código funciona en local pero no pasa las pruebas

### ISSUE THREAD

**Issue by eduardoc120** [midudev/adventjs-issues#128]
`export default function isValid(letter) {`
`const regex = /^.*\([a-zA-zñ]+\).*$/;`
`return regex.test(letter);`
`}`

Al ejecutar el código, me da esta respuesta: **¿Estás seguro que "(muñeca) consola bici" no es válido?**

En local la función devuelve true con ese input, además cambie el código y me da la misma respuesta

`export default function isValid(letter) {`
`if (letter == "(muñeca) consola bici") return true`
`const regex = /^.*\([a-zA-zñ]+\).*$/;`
`return regex.test(letter);`
`}`

**Comment by midudev** [comment]
El problema es que la regex no tiene en cuenta palabras con acentos.

Prueba con esto:
`bici coche (balón) bici coche peluche`
