### ISSUE TITLE
Error de ejemplo en el reto 20

### ISSUE THREAD

**Issue by tomtobac** [midudev/adventjs-issues#129]
Segun el ejemplo
```js
pangram('Jovencillo emponzoñado y con walkman: ¡qué figurota exhibe!') // true
```

Y debería devolver `false` ya que no contiene la letra S.

**Comment by palawer** [comment]
Yo he entrado hace un rato y ya está corregido:

> Jovencillo emponzoñado y con walkman: ¡qué figurota exhibes!

**Comment by tomtobac** [comment]
> Yo he entrado hace un rato y ya está corregido:
> 
> > Jovencillo emponzoñado y con walkman: ¡qué figurota exhibes!

Cierto, parece que ya está arreglado. Cierro la issue 👍
