### ISSUE TITLE
Diseño responsive

### ISSUE THREAD

**Issue by ya1k96** [midudev/adventjs-issues#13]
![Screenshot_2021-12-01-17-59-22-390_com android chrome](https://user-images.githubusercontent.com/41270347/144313190-cbaad485-a7f5-48d2-b851-fc127014f576.jpg)

**Comment by davorpa** [comment]
Coincido al igual que en #8, #40, #34

En vertical se ve bastante feo, incompatible para teclear en el editor.

![Screenshot_20211202-165222](https://user-images.githubusercontent.com/3125580/144457490-5c18c780-ef09-4012-a59f-06539e53ef10.png)


En horizontal algo mejor aunque el espacio se lo come todo el teclado nativo.

![Screenshot_20211202-165235](https://user-images.githubusercontent.com/3125580/144457573-5b650885-a7b1-4c66-b66c-0b3e82c01530.png)

Habría que darle una pensada al mobile first

**Comment by midudev** [comment]
Ya he adaptado el sitio a responsive. 👍

**Comment by davorpa** [comment]
Si!! ya se vé mejor y es tope usable. Gracias.

![Screenshot_20211205-194745](https://user-images.githubusercontent.com/3125580/144759758-bdf95733-f608-4af1-834f-8b2de1e72d41.png)
![Screenshot_20211205-195015](https://user-images.githubusercontent.com/3125580/144759769-2346686e-fd61-4abc-8059-8882ff62cfd0.png)
