### ISSUE TITLE
adventjs5. no pasa los test pero funciona bien 

### ISSUE THREAD

**Issue by guillesg** [midudev/adventjs-issues#132]
Los test que yo pongo salen bien en la terminal de vs code. Pero al ponerlo a comprobar con los test de la página, me salen errores. 

function daysToXmas(date) {
    
    return (Date.parse('Dec 25, 2021') - Date.parse(date))/1000/60/60/24
}

console.log(daysToXmas('2023-12-02'))

El resultado aquí sería -707.
Felices fiestas.

**Comment by davorpa** [comment]
Y el redondeo???? te animo a leer otra vez el enunciado del ejercicio

- `Math.trunc`
- `Math.round`
- `Math.ceil`
- `Math.floor`
- `Number(n.toFixed(0))`

**Comment by guillesg** [comment]
Intentaré arreglarlo y voy a leer el enunciado de nuevo, tengo dudas aun pero gracias por ayudar

**Comment by davorpa** [comment]
otro consejo de Pro 😉

Debido a como funcionan las operaciones en coma flotante es mejor hacer las mínimas divisiones posibles para no perder precisión. 
Entonces optimizamos con:  `(date2 - date1) / (1000 * 60 * 60 * 24)`

Otro es usar restas mejor que sumas para evitar concatenaciones si lo que llega no es un número

**Comment by guillesg** [comment]
Listo amigo, pase el test luego de dos semanas. Intenté seguir haciendo los demás y se me fue olvidando. También corregí lo de tantas divisiones. Muchas gracias por la ayuda.
