### ISSUE TITLE
feature: dificultad dentro de cada reto

### ISSUE THREAD

**Issue by pasagedev** [midudev/adventjs-issues#136]
Cuando se completa un reto se puede pasar al siguiente inmediatamente (lo cual está genial), pero para saber el nivel de dificultad del nuevo reto, es necesario volver a la página principal donde están todos.
Sería interesante también tener el nivel de dificultad dentro de cada reto, por ejemplo al final de la descripción ;)

Saludos!

**Comment by davorpa** [comment]
+1

Yo pondría en todos los detalles de los retos como una pestaña lateral obliqua con la dificultad y color a modo background

o también simplemente un badge al lado del título del reto como en el índice
