### ISSUE TITLE
Bug Reto 25

### ISSUE THREAD

**Issue by armap99** [midudev/adventjs-issues#140]
Aunque el código pase todas las pruebas de ejemplo, no es aceptado como una respuesta valida. 
En la consola aparece lo siguiente.
![image](https://user-images.githubusercontent.com/39971883/147389562-2bc46f8f-33bf-473e-b353-f8a620eaf384.png)

**Comment by palawer** [comment]
¿Puedes compartir el código para que podamos ver qué puede estar fallando?

**Comment by armap99** [comment]
`function canMouseEat(direction, game) {
  let x = 0
  let y = 0
  for(let i=0; i< game.length;i++){
        if(game[i].indexOf('m') !==-1){
            y=i
            x=game[i].indexOf('m')
        }
    }
  if(direction === 'up'){
      y-=1 
  }
  if(direction === 'down'){
      
      y+=1
  }
  if(direction === 'right'){
      x+=1 
  }
  if(direction === 'left'){
      x-=1 
  }
  return game[y][x] === '*'
}`
