### ISSUE TITLE
Reto 3 - Blank spaces between parentheses

### ISSUE THREAD

**Issue by saulr9** [midudev/adventjs-issues#144]
Hola @midudev primero que todo, darte gracias por excelente iniciativa. La descubrí un poco tarde pero espero poder seguir haciendola.

Te comento un poco sobre el reto 3 y quizás un issue que haya ( posiblemente esté equivocado )

Mi solución: 

```
export default function isValid(letter) {
  const regExp = /\((.*)\)/i;
  const grinchChar = ['{', '[', '()'];
  
  // if letter doesn't have text between parenthesis return false, not valid letter.
  if (!regExp.test(letter)) return false;
  
  let grinchHand = grinchChar.some( char => {
    return letter.includes(char);
  })
  return grinchHand ? false : true;
}
```

Al ejecutar ese codigo en adventJs. Pasa los tests. Sin embargo probando diferentes casos en RunJs al yo pasarle una cadena como:
`const letter7 = "(          ) bici coche balón"`  me retornaria una letter válida.  Que me parece no deberia ser válida ya que dentro de las condiciones está "Para saber si una carta es válida ✅, debes comprobar que los paréntesis cierran correctamente y que, además, **no vayan vacíos**"

Creo se solucionaria ese caso agregando una condición como `if (!regExp.test(letter) || /\(([\s])\)/i.test(letter)) return false;` para validar que dentro de parentesis no hayan multiples espacios vacios(igual y se pueden mejorar las expresiones regulares).

Me gustaria saber tu opinión al respecto.
Gracias!

**Comment by davorpa** [comment]
related with #45 and #58
