### ISSUE TITLE
reto 3

### ISSUE THREAD

**Issue by chriseduardo** [midudev/adventjs-issues#150]
const cartas = [
  "bici coche (balón) bici coche peluche",
  "(muñeca) consola bici",
  "bici coche (balón bici coche",
  "peluche (bici [coche) bici coche balón",
  "(peluche {) bici",
  "() bici"
]

cartas.forEach( carta => {
	let estado = carta.match(/\([^\)^\{^\[]+\)/)?.length>0;
  console.log(carta,estado)
})

<img width="318" alt="image" src="https://user-images.githubusercontent.com/99278865/160384167-d27b6468-c270-4294-9f37-7b0f763ea240.png">

**Comment by roberto2003al** [comment]
Hola, intente tu solución pero todo da verdadero y solo las primeras 2 son verdaderas:

![image](https://user-images.githubusercontent.com/12976325/192190674-c39df836-b756-4498-bb44-458197006ab3.png)
