### ISSUE TITLE
Reto 2 no reconoce mi código :(

### ISSUE THREAD

**Issue by chrisdev3002** [midudev/adventjs-issues#151]
El reto 2 no reconoce mi código y lo he probado en la consola del navegador :(

dejo el código, saludos midus!

`export default function listGifts(letter) {
  let regalosObj = {}
  const gifts = letter.split(" ")
  for(gift of gifts){
    const regalo = gift.trim()
    if(regalo.substring(0,1) !== '_'){
      regalosObj[regalo] ??= 0
      regalosObj[regalo] += 1
    }
  }
  return regalosObj
}`

**Comment by oespino** [comment]
Creo que te falta declarar la variable `gift` en el `for ... of` con `let` o `const`

![image](https://user-images.githubusercontent.com/37581410/163485444-6c814a9e-a2e6-4765-af5a-436f4c3d3a06.png)
