### ISSUE TITLE
Reto 2

### ISSUE THREAD

**Issue by alexmarcelli** [midudev/adventjs-issues#152]
Soy principiante en esto de la programación. Intenté hacer el reto 2 y dice que no tengo en cuenta los espacios dobles, este es mi código: 
let array = letter;
    if (array.includes('  ')) {
        array = array.split('  ').filter( juguete => !juguete.includes('_'));
    } else {
        array = array.split(' ').filter( juguete => !juguete.includes('_'));

    }
    
    console.log(array);

    function contarOcurrencias (datos) {
        return datos.reduce((a, d) => (a[d] ? a[d] += 1 : a[d] = 1, a), {})
    }

    let objeto = contarOcurrencias(array);

    return objeto;

**Comment by Roma-it** [comment]
Hola, pareciera que no estas filtrando los espacios vacios, cuando haces el split por espacios, si hay dos espacios juntos o mas, te genera elementos en el array que consisten en espacios vacios.
Te sugiero hacer un primer filtro de esta forma> const arrLetter = letter.split(' ').filter(gift => !gift.startsWith("_") && gift.length)
