### ISSUE TITLE
Reto 3 - no reconoce la expresion regular 

### ISSUE THREAD

**Issue by AyrtonFidel9** [midudev/adventjs-issues#153]
![image](https://user-images.githubusercontent.com/70295855/163736810-24079abf-e81a-4fd1-aef9-f9d2e0c537fd.png)

**Comment by roberto2003al** [comment]
Me quito el sombrero, porque:
 - intuiste que todas las cartas incluirían paréntesis lo que te permitió solo preocuparte por las correctas haciendo el codido de 2 lineas.

Pero si tu reto estaba en español como el mio, entonces te falto agregar ó dentro de tus caracteres posibles, [a-zA-ZñÑó]

lo curioso es que la que te tendria que salir mal es:
"bici coche (balón) bici coche peluche" // -> ✅
