### ISSUE TITLE
Reto#3 si pruebo en consola todo valída 

### ISSUE THREAD

**Issue by cayorivera** [midudev/adventjs-issues#155]
// la instrucción dice debes comprobar que los paréntesis cierran correctamente y que, además, no vayan vacíos.

export default function isValid(letter) {
 // ¡No dejes que el Grinch gane! 
 const comprobacion = /\([a-záéíóúñ]+\w{1}\)/g
 if(comprobacion.test(letter)) {
   return true
 } else {
   return false
 } 
}

**Comment by cayorivera** [comment]
//ahora si paso
export default function isValid(letter) {
// ¡No dejes que el Grinch gane!
const comprobacion = /([a-záéíóúñ]+\w{0}) /g
if(comprobacion.test(letter)) {
return true
} else {
return false
}
}

**Comment by roberto2003al** [comment]
Tu codigo da True en varias que son realmente False
![image](https://user-images.githubusercontent.com/12976325/192188401-fb4a5346-a877-4088-a799-e402b6f13bf0.png)
