### ISSUE TITLE
No detecta mi código, Reto 3

### ISSUE THREAD

**Issue by annicole** [midudev/adventjs-issues#156]
function isValid(letter) {
 // ¡No dejes que el Grinch gane!
  let gift = [];
  let c1;
  for(let i=0;i<letter.length;i++){
    c1= letter[i];
    switch(c1){
    	case '{':
      case '[':
      	return false;
     	case '(':
      	if(gift.length === 0){
        	gift.push(c1);
        }else{
        	return false;
       }	
      break;
      case ')':
      	if(gift.length > 2) return true;
      default:
      	gift.push(c1);
       break;
    }
  }
 return false;
}

**Comment by annicole** [comment]
![image](https://user-images.githubusercontent.com/23502548/175611897-fe69c2cb-41cd-48d8-a88a-fd8e4977b098.png)

**Comment by roberto2003al** [comment]
Tu codigo da Falso en la oracion: 
bici coche (balón) bici coche peluche, 
Y debia dar como verdadero.

![image](https://user-images.githubusercontent.com/12976325/192187498-49ba7383-267a-4181-959d-12f5645bced6.png)

**Comment by Roma-it** [comment]
Es sorprendente y extraordinario a la vez como cada uno piensa la solución de formas tan distintas y como es posible llegar al mismo resultado de maneras tan diversas. Comento esto porque al ver el código de @annicole  me doy cuenta que nunca considere explorar esa posibilidad y lo resolví de una forma completamente distinta. Eso me encanta de la programación :)
