### ISSUE TITLE
No muestra correctamente el número de usuarios que han completado un reto

### ISSUE THREAD

**Issue by SEOAlexRamon** [midudev/adventjs-issues#158]
¡Buenos días! :wave:

Primeramente, felicitarte por el proyecto. :confetti_ball:
Estos días he observado que siempre aparece "Completado por 0 usuarios".

![image](https://user-images.githubusercontent.com/37023161/181434842-059777ab-f272-4130-8023-fe95a5fcf6d1.png)

¡Es un error mínimo, pero todo sea mejorar! :wink:

Un saludo.

**Comment by midudev** [comment]
Ya está arreglado. 👍
