### ISSUE TITLE
Soporte Typescript

### ISSUE THREAD

**Issue by AaronPerezPerez** [midudev/adventjs-issues#16]
Al añadir tipado, los tests fallan por alguna razon. Aún el editor soportando TS.
Código de ejemplo:

```typescript
type Sheep = {
  name: string
  color: "rojo" | "azul"
}

export default function contarOvejas(ovejas) {
  return ovejas.filter(({name, color}) => {
    const isRed = color === 'rojo'
    const includesA = name.toLowerCase().includes('a')
    const includesN = name.toLowerCase().includes('n')
    const includesRequiredLetters = includesA && includesN
     
    return isRed && includesRequiredLetters 
    })
}
```

Con solo añadir el tipado, aún sin usarlo, ya da error en los tests.

**Comment by midudev** [comment]
Sí, ahora mismo no soporta TypeScript. Pero lo miraré a ver si lo consigo. :)

**Comment by midudev** [comment]
Hemos añadido soporte a TypeScript en la nueva edición de AdventJS.
https://adventjs.dev/
