### ISSUE TITLE
Una vez resuelto el nivel, seria bueno poder ver las soluciones de los demas

### ISSUE THREAD

**Issue by Roma-it** [midudev/adventjs-issues#165]
Midu, gran iniciativa, me divierto mientras practico y aprendo!!! **Gracias por eso!**

Seria ideal que, una vez que el usuario resolvio un nivel, se habilite la posibilidad de ver como otras personas resolvieron el reto, es una retroalimentacion muy buena para conocer mas posibilidades y mas formas de encarar cada desafio.

**Comment by roberto2003al** [comment]
O al menos las mejores soluciones desde distintos puntos de vista; rendimiento, memoria, legibilidad, extension ect...

**Comment by jorgegiro** [comment]
Viendo que hay un ranking, estaría bien por lo menos verlas una vez finalice el adviento. De esa forma, se podría cerrar el ranking definitivo sin que nadie "copie" la solución de otros.
