### ISSUE TITLE
Agregar un caso secreto de prueba

### ISSUE THREAD

**Issue by fram7** [midudev/adventjs-issues#17]
Si se hace un return de la respuesta literal pasa, se que no es lo correcto, pero podría agregar un valor extra de dificultad

<img width="1137" alt="Midu" src="https://user-images.githubusercontent.com/10606288/144338361-acbf783e-21ad-4e50-9a26-c34119d6c7a7.png">

**Comment by midudev** [comment]
Todos los retos ya tienen casos secretos. :)
