### ISSUE TITLE
I think that my answer is right

### ISSUE THREAD

**Issue by LeodanLVL** [midudev/adventjs-issues#170]
export default function learn(HTH, Cursos) {
 c1=0,c2=0,dif=9999999999;
    Cursos.forEach((element, index) => {
        
        Cursos.forEach((element2, index2) => {
                if(index!=index2)
                {
                    if(element !=0 && element2 !=0)
                    {

                    
                    if(HTH-(element+element2)>=0&&HTH-(element+element2)<dif)
                    {
                        c1=index;
                        c2=index2;
                        dif=HTH-(element+element2);
                    }
                }
                }
       
        });
       
    });
    //console.log(`Curso #: ${c1} y Cruso #: ${c2}`);
    if(dif==9999999999)
    {
        return null;
    }else
    {
        return[c1,c2]

    }
}

**Comment by midudev** [comment]
That's what we always think! :D Or you have bad formatted the code or the solution is not correct.
