### ISSUE TITLE
Error al crear usuario 

### ISSUE THREAD

**Issue by imjpfeliciano** [midudev/adventjs-issues#171]
Al momento de iniciar sesión con Github y redireccionar al callback, la pantalla se queda pegada en `Verificando datos`

La url tiene el siguiente formato:

`https://adventjs.dev/callback?error=server_error&error_description=Failed%20to%20generate%20temporary%20magic%20credential.&provider=github`

Y en la consola tenemos el siguiente error:
![image](https://user-images.githubusercontent.com/6007230/199562584-f711c160-8107-4f3b-a70d-86562c1be9c8.png)

**Comment by midudev** [comment]
Era un problema temporal con Magic y ya debería estar arreglado.
