### ISSUE TITLE
Reto 3: solución considerada inválida

### ISSUE THREAD

**Issue by mvicens** [midudev/adventjs-issues#172]
En el [reto 3](https://adventjs.dev/challenges/03), no me da por bueno (muestra "El código no parece correcto... ¡Revísalo!" y, a continuación, "Haz cambios en el código para ejecutar los tests automáticos...") el siguiente código:

```js
export default function isValid(letter) {
  if(letter.includes('{') || letter.includes('[') || letter.includes('()'))
    return false;

  let n = 0;
  for (char of letter) {
    if (char == '(') 
      n++;
    else if (char == ')') {
      n--;
      if (n < 0)
        return false;
    }
  }
  return !n;
}
```

**Comment by midudev** [comment]
Algo te falla en el código, revísalo bien o pásate por Discord en #adventjs para que te echen una mano. https://discord.gg/midudev

**Comment by mvicens** [comment]
Testeé por mi cuenta todos los ejemplos y pasaban correctamente. ¿Puedes, por favor, pasarme un _string_ con el que no dé el resultado esperado?

No tengo cuenta de Discord.
