### ISSUE TITLE
Reto 2

### ISSUE THREAD

**Issue by mandril888** [midudev/adventjs-issues#174]
Buenas!! Primero de todo gran iniciativa :)

Tengo este código que en principio funciona bien pero no pasa los test. He probado con diferentes "cartas/letters" y me funciona correctamente:

`export default function listGifts(letter) {
  const listGiftsObj = {};
  letter
    .replace(/\ +/g, ' ')
    .split(' ')
    .filter(gift => !gift.includes('_'))
    .forEach(el => {
      if (el in listGiftsObj) listGiftsObj[el] += 1;
      else listGiftsObj[el] = 1;
    });

  return listGiftsObj;
}`

¿Alguna ayuda?

**Comment by midudev** [comment]
Entra a https://discord.gg/midudev en el canal de #adventjs y comenta allí para que te ayuden.
