### ISSUE TITLE
El texto de Puntos conseguidos y Ejecutando tests deberían de estar en ingles

### ISSUE THREAD

**Issue by jlallaucca** [midudev/adventjs-issues#176]
![image](https://user-images.githubusercontent.com/46771690/205146475-dc7668ba-f59c-4d87-8977-c66474d322a6.png)

![image](https://user-images.githubusercontent.com/46771690/205146279-e9535d5e-0eb7-42e6-8f5a-ed5a56c275bd.png)

**Comment by midudev** [comment]
Hecho!
