### ISSUE TITLE
Error en el link de Platzi

### ISSUE THREAD

**Issue by jdoavila** [midudev/adventjs-issues#178]
El Link hacia platzi está mal escrito, dice: https://**platiz**.com/midudev, y creo que debería ser: platzi.com/midudev

Adjunto una captura de pantalla para comprobarlo.

![Screenshot 2022-12-01 at 23 47 25](https://user-images.githubusercontent.com/1307456/205223937-98cc5a4c-a0b7-4655-80a1-dfb27b7b9506.png)

**Comment by midudev** [comment]
Fixed! Gracias!
