### ISSUE TITLE
Los test me arrojan error tanto en Javascript como en Typescript.

### ISSUE THREAD

**Issue by D3vaya** [midudev/adventjs-issues#18]
# Gracias por la iniciativa  ❤️. Saludos desde 🇨🇱

**Ejemplo TS**

```ts
type Sheep = {
  name: string
  color: string
}
const ovejas: Sheep[] = [
  { name: 'Noa', color: 'azul' },
  { name: 'Euge', color: 'rojo' },
  { name: 'Navidad', color: 'rojo' },
  { name: 'Ki Na Ma', color: 'rojo'}
]
export default function contarOvejas(ovejas) {
  return ovejas.filter(({name, color}) => color === "rojo" && name.includes("a"))
}

const ovejasFiltradas = contarOvejas(ovejas)

console.log(ovejasFiltradas)
```

**Ejemplo JS**

```js

const ovejas = [
  { name: 'Noa', color: 'azul' },
  { name: 'Euge', color: 'rojo' },
  { name: 'Navidad', color: 'rojo' },
  { name: 'Ki Na Ma', color: 'rojo'}
]

export default function contarOvejas(ovejas) {
  return ovejas.filter(({name, color}) => color === "rojo" && name.includes("a"))
}

const ovejasFiltradas = contarOvejas(ovejas)

console.log(ovejasFiltradas)
```

**Comment by D3vaya** [comment]
<img width="1672" alt="Captura de Pantalla 2021-12-01 a la(s) 22 06 47" src="https://user-images.githubusercontent.com/6782712/144339158-34a5af81-840a-423b-a71e-23c53a467091.png">

**Comment by dadadev88** [comment]
Solo modifica el contenido de la función y asegurate de devolver el resultado esperado, el test se ejecutará automaticamente

**Comment by ZajithCorro** [comment]
Creo que no estas tomando en cuenta que el problema dice: _**que su nombre contenga las letras n y a, sin importar el orden, las mayúsculas o espacios**_. Con la función que hiciste solo evalúas que se encuentra la letra **a** dentro del nombre, pero no la letra **n**  🤔

**Comment by Bayzon88** [comment]
Tal parece que no funciona en firefox, estuve un buen rato pensando que habia algo mal con mi codigo.

**Comment by ivorpad** [comment]
@ZajithCorro 

### "Haz una función que devuelva una lista con todas las ovejas que sean de color rojo y que su nombre contenga las letras _n y a_"


```js
function contarOvejas(ovejas) {
  return ovejas.filter(oveja => oveja.color === "rojo" && oveja.name.toLowerCase().includes("na"));
}
```

**Comment by ZajithCorro** [comment]
> @ZajithCorro 
> 
> 
> 
> ### "Haz una función que devuelva una lista con todas las ovejas que sean de color rojo y que su nombre contenga las letras _n y a_"
> 
> 
> 
> 
> 
> ```js
> 
> function contarOvejas(ovejas) {
> 
>   return ovejas.filter(oveja => oveja.color === "rojo" && oveja.name.toLowerCase().includes("na"));
> 
> }
> 
> ```

Funcionaria, pero también el problema comenta que no importa el orden o si hay espacios en blanco. Porque aquí solo compruebas que se encuentre **na**, pero no encuentra todo los demás casos

**Comment by D3vaya** [comment]
@ZajithCorro @Bayzon88 @ivorpad @dadadev88  gracias por los comentarios muchachos ❤️
