### ISSUE TITLE
Diferencia de puntos entre resolver en TS y JS

### ISSUE THREAD

**Issue by MauricioBorawski** [midudev/adventjs-issues#181]
Mientras hacia los retos note que resolverlos en TS te da una cantidad significativamente menor de puntos que resolverlos en JS.

Adjunto unas imagenes de ambos codigos y sus respectivos resultados.

![adventJs Ex4 JS](https://user-images.githubusercontent.com/84733593/205515783-39a203b5-7c3c-40d2-9056-2dfae10c7eca.png)
![image](https://user-images.githubusercontent.com/84733593/205515797-514828d1-acf4-4e32-bee7-bc361680d2f9.png)
![adventJs Ex4 TS](https://user-images.githubusercontent.com/84733593/205515784-19bc7bda-4350-4736-93dc-e59edbbed056.png)
![image](https://user-images.githubusercontent.com/84733593/205515792-82668419-3bf7-4132-a8c1-4b7c5a861608.png)

**Comment by j-testdev** [comment]
Me ha pasado igual en otro reto, pero no había tanta diferencia de puntos. Creo que no se está teniendo en cuenta que tiene que compilar el ts para los tests

**Comment by AaronPerezPerez** [comment]
Yo tengo el mismo problema, tengo varios con buenas puntuaciones individuales, pero la global se me queda a 10

**Comment by cafeteru** [comment]
Me paso a mí también en el reto 08

**Comment by midudev** [comment]
En general ya está solucionado.

Sin embargo es posible que a veces pueda ser ligeramente diferente, ya que el compilador de TypeScript formatea algo el código.
