### ISSUE TITLE
Private tests passed sometimes and not passed other times | Challenge 5

### ISSUE THREAD

**Issue by HectorCavilla** [midudev/adventjs-issues#183]
When solution is submitted, the private tests are showed as passed for example 2 of 4 clicking Submit buttón, trying again with no changes on the solution I am getting 2 different test passed and the 2 already passed are not passed now (example)

<img width="946" alt="Screenshot_20221205_054738" src="https://user-images.githubusercontent.com/11187069/205759475-95465a10-1451-450e-8c89-b4a91c1f3cdc.png">
<img width="943" alt="Screenshot_20221205_054750" src="https://user-images.githubusercontent.com/11187069/205759478-3113d7d6-511c-4473-a1c1-c654fadbe366.png">
<img width="945" alt="Screenshot_20221205_054803" src="https://user-images.githubusercontent.com/11187069/205759479-7b239609-aba4-4513-a283-da2694244767.png">
<img width="948" alt="Screenshot_20221205_054819" src="https://user-images.githubusercontent.com/11187069/205759482-077b7454-4e4b-44f6-b9d6-ccaa64a99ee2.png">

`function getMaxGifts(giftsCities, maxGifts, maxCities) {
  return giftsCities.reduce((prev, curr) => {
    let sum = prev + curr
    
    return (sum <= maxGifts)
    ? sum
    : (curr > prev && curr <= maxGifts)
      ? curr
      : prev
  }, 0)
}

const giftsCities = [50, 70, 30]
const maxGifts = 100
const maxCities = 3

getMaxGifts(giftsCities, maxGifts, maxCities)`

All the public tests are always passed!

**Comment by midudev** [comment]
This is because your solution is not completely correct. Secrets tests are random.
