### ISSUE TITLE
https://2021.adventjs.dev/challenges/01

### ISSUE THREAD

**Issue by INGSIS** [midudev/adventjs-issues#184]
![image](https://user-images.githubusercontent.com/5896830/205933985-438b7d62-58a6-48bc-b472-5a649d2d55b9.png)

**Comment by INGSIS** [comment]
Donde está la falla ?

**Comment by INGSIS** [comment]
![image](https://user-images.githubusercontent.com/5896830/205934307-3cd65d5b-757b-4444-b6ff-6257d395019d.png)

**Comment by INGSIS** [comment]
![image](https://user-images.githubusercontent.com/5896830/205934624-32560862-59bd-4313-af9f-1c27e28fe2d6.png)

**Comment by paulusrex** [comment]
Al menos te falta un `let` en el `for` 
`for(let ovejas = ovejas.lenght-1; i >= 0; i--({}`

**Comment by midudev** [comment]
Como dice @paulusrex, el código se ejecuta en modo estricto y, por lo tanto, necesitas poner el `let` en el for.
