### ISSUE TITLE
Poder ver maxima puntuación por reto

### ISSUE THREAD

**Issue by UrielJavier** [midudev/adventjs-issues#185]
Estaria muy bien poder saber el maximo puntaje conseguido en cada reto, pero a nivel de comunidad, asi nos picamos y podemos ver si se puede mejorar mas nuestra solucion.

**Comment by marsidev** [comment]
Algo así había propuesto en Discord
![image](https://user-images.githubusercontent.com/56328053/207639385-920f0ae4-dacc-4184-a9b6-5fe00f970eb3.png)
