### ISSUE TITLE
Ver puntos acumulados y numero clasificación

### ISSUE THREAD

**Issue by NeusRomanP** [midudev/adventjs-issues#186]
No se si lo habrán sugerido ya pero estaría bien poder ver el total de puntos acumulados entre todos los retos. Además de que salga en la clasificación el numero de posición de cada uno.

**Comment by midudev** [comment]
<img width="1189" alt="CleanShot 2022-12-11 at 01 23 31@2x" src="https://user-images.githubusercontent.com/1561955/206880695-bb78df08-3e0b-4a14-b05d-b24fa85d19b3.png">

Ya disponible en la página de Clasificación.
