### ISSUE TITLE
Redireccionar a challenges page👍 

### ISSUE THREAD

**Issue by aarrieth** [midudev/adventjs-issues#19]
![Captura](https://user-images.githubusercontent.com/20328321/144346622-1fe1b207-3f54-4037-a9cc-445ba97076fd.PNG)

Una vez que la solución pase los test correctamente y se envíe el ejercicio, nos direccione a la página de challenges.

**Comment by midudev** [comment]
Vamos a mostrar una modal por si la gente quiere compartir la solución. :)
