### ISSUE TITLE
During challenge 4 a code that seems valid gives error

### ISSUE THREAD

**Issue by paulusrex** [midudev/adventjs-issues#191]
With this code, that seems valid, on challenge 4 adventJS gives this error response `Code has to be compatible with ES2017 spec: There is no optional chaining nor nullish support for now.`

``` 
function fitsInOneBox(boxes) {
  const sides = ['l', 'w', 'h']
  const allValues = boxes.map(Object.values).flat()
  const maxLength = Math.max(...allValues) + 1
  const weightedBoxes = boxes
    .map(box => {
      const weight = box.l * maxLength * maxLength + box.w * maxLength + box.h
      return { ...box, weight }
    })
  weightedBoxes.sort((a, b) => a.weight - b.weight)
  const willFit = (a, b) => sides.every(side => a[side] < b[side])
  for (let i = 1; i < weightedBoxes.length; i++) {
    if (!willFit(weightedBoxes[i - 1], weightedBoxes[i])) return false
  }
  return true
}
```

![Screenshot 2022-12-09 at 10 24 36](https://user-images.githubusercontent.com/45286922/206669627-015cddeb-2bd2-4ccc-b08d-649bf43a8c92.png)

**Comment by danilupion** [comment]
Hi @paulusrex had a look and apparently it's the spread operator that is causing this error (line 8 "...box" in your code). AFAIK the spread operator is ES6 though 🤷

**Comment by paulusrex** [comment]
You are right. I looked at the [proposals of TC39](https://github.com/tc39/proposals/blob/HEAD/finished-proposals.md), and the problem is the object spread operator, which is part of JS since ES2018 standard. 
The spread operator for arrays seems to be the spread of ES6 only.

**Comment by paulusrex** [comment]
Only to add complete the issue the final working line 8 is `return Object.assign(box, {weight})`
Thank you @danilupion for the lead
