### ISSUE TITLE
Ver resolución subida

### ISSUE THREAD

**Issue by ezebinker** [midudev/adventjs-issues#20]
Estaría muy bueno poder ver la resolución que subiste de cada ejercicio al volver a hacer click en el desafío completado.
Por el momento lo que hace es volver a poner el código en el estado inicial (no completado). 

Más allá de esto, excelente iniciativa Miguel!

**Comment by davidmaillo** [comment]
+1

**Comment by midudev** [comment]
:) Ya hemos añadido esta funcionalidad.

**Comment by ezebinker** [comment]
Excelente!
