### ISSUE TITLE
All tests passed for specific task except hidden ones

### ISSUE THREAD

**Issue by GIvanovAstound** [midudev/adventjs-issues#208]
All tests passed for specific task except hidden ones (what is the purpose of hidden tests and how we may see them)?

Task name: Challenge #5: Optimizing Santa's trips

Task Code:
 

``` function getMaxGifts(giftsCities, maxGifts, maxCities) {
  const sortedGiftCities = giftsCities.sort((a, b) => b - a)
  let sum = 0
  let iterations = 0
  
  sortedGiftCities.forEach((city, index) => {
    if (sum + city <= maxGifts && iterations <= maxCities) {
      sum += city;
      iterations++;
      
      if(!sortedGiftCities[index+1] || iterations === maxCities) return
      
      if (index > 1 && sum + sortedGiftCities[index+1] > maxGifts) {
        sum -= city;
        iterations--;
      }

    }
  })

  return sum
} 
```

Task results: https://prnt.sc/BWx7QCF9POit 

How can we understand what is our mistake in case there is actually, since all other tests are passing, please advice us?

**Comment by midudev** [comment]
That's because your code is not correct. The idea of hidden tests is that you solve correctly the algorithm and you can cheat by sending manually the expect results.

**Comment by GIvanovAstound** [comment]
Well I see your point about cheating but as you see - I am writting code which is not cheat
But right now there is no clue of what the problem might be.
