### ISSUE TITLE
There is no information what is the maximum points you can earn from a challenge

### ISSUE THREAD

**Issue by TripleG** [midudev/adventjs-issues#211]
When the challenge is complete only the points granted are displayed.
It would be more convenient to show what is the maximum possible points amount, so I can try further to improve/optimize my solutions.

**Comment by joseluisnoguera** [comment]
If the maximum points that one can earn is difficult, an alternative could be to have a filter by challenge in the leaderboard, so people themselves give the maximum points that can be earned.
