### ISSUE TITLE
Soluciones rechazadas porque no se cumplen test secretos??? En serio???

### ISSUE THREAD

**Issue by hernandez-alex** [midudev/adventjs-issues#212]
Creo que hay que tratar de evitar colocar test secretos, como saber cual es la falla de tu código si no sabes lo que se esta evaluando, pueden ser millones de cosas las que fallen desde una simple validación hasta cualquier cosa inimaginable que evalue el sistema

**Comment by midudev** [comment]
En serio. Los tests secretos es típico en este tipo de plataformas ya que, de lo contrario, se podría devolver los resultados directamente dependiendo de los parámetros.

Eso es básico. Y entiendo la frustración, pero el tema es que significa que no has completado el reto correctamente. :D
