### ISSUE TITLE
Accesibilidad con lectores de pantalla

### ISSUE THREAD

**Issue by Marc2p** [midudev/adventjs-issues#22]
Los resultados de los tests no son accesibles con lectores de pantalla como NVDA, seguramente por unos aria hidden y display none que hay por ahí. Sería interesante que lo fueran, enriquecería la experiencia al no tener que testear el código en un entorno externo como Node o la consola del navegador para saber qué está fallando.
También adiero a #12 un botón de ejecutar sería más accesible para comprender mejor el funcionamiento
También adiero a #20 y #9
Te felicito por el proyecto, a ver si logro completar los 25.

Gracias!

**Comment by midudev** [comment]
¡Hola Marc! No vamos a añadir otro botón para ejecutar los tests, pero he movido los tests debajo del editor y ahora deberían aparecer siempre, además de hacerlos más descriptivos.
