### ISSUE TITLE
Tengo un error con la siguiente solucion

### ISSUE THREAD

**Issue by JosueMoora** [midudev/adventjs-issues#222]
hola midu estoy intentado resolver el reto #1 pero me da error el test #10 y si recargo la pagina y envio de nuevo la solucion, pasa el test 10 pero falla el 12, te puedo dejo la solucion para que la revises, a ver que pueda ser 
function findFirstRepeated(gifts) {
    const newGift =  []
    for (const id of gifts){
      const find =  newGift.find(g => g === id)
     if ( find) {
        return find
    } 
    newGift.push(id)
    }
    return -1
  }

**Comment by gonzalo1987** [comment]
Buenas, 
esto igual iría mejor en el discord, ya que este repo es para problemas del proyecto, pero te aconsejo mirar tu código con estos parámetros de entrada: 
[2, 0, 3, 0, 3, 2, 3]

¡Un saludo y ánimo 💪!

**Comment by JosueMoora** [comment]
Buenas, 
vale gracias,  ya logre solucionarlo la proxima escribo la duda por discord :)
Un Saludo!
