### ISSUE TITLE
Se me ha buggeado al aportar una solución (Reto #1).

### ISSUE THREAD

**Issue by Gonzalo1987** [midudev/adventjs-issues#223]
Estaba yo intentando mejorar la solución, y había llegado a esta solución: 

<details>
  <summary>Spoiler warning</summary>

```return gifts.find((gift, i) => gifts.indexOf(gift) !== i) ?? -1;``` 

(*) *También he probado a usar filter()[0] con sorprendentemente un resultado casi idéntico*
</details>

Me daba complejidad 1, sin errores y buen rendimiento, una puntuación total de 360.

Pero me he puesto a quitar los espacios e intentar recortar para bajar los carácteres del resultado, con lo que he llegado a una solución muy similar 
<details>
  <summary>Spoiler warning</summary>

```return gifts.find((g, i)=>gifts.indexOf(g)!=i)??-1```
</details>

Pues me ha guardado el resultado con la misma puntuación, pero ahora siempre que uso tanto una cosa como la otra me dice... Que esa línea ocupa más de 160 caracteres (En realidad ocupa toda la línea 49), que tiene una complejidad de 4 (muy extraño, porque antes me estaba diciendo que la complejidad era 1, y a parte aunque se determinara que 'ciertas funciones' le añadieran más complejidad esta no podría ser 4, a lo sumo 3), e incluso con el primer resultado dice que hay declaraciones usando 'var'. Con lo que da la sensación de que algo se ha quedado bug.

Por si lo puedes revisar, el resultado me da un poquillo igual. Mil gracias midu por tu tiempo, eres un ídolo!

Edit: Haciendo más pruebillas y tal, he conseguido que el código que he puesto arriba vuelva a dar complejidad 1 y el compilador elimine los errores de vars y demás, pero parece por lo descrito que en ocasiones tiene un comportamiento errático. Además parece que el comportamiento errático se queda como 'atascado', porque he tenido que quitar el código que no le gustaba para 'engañar al compilador' y al volver a escribirlo cuando ya se ha limpiado ha dejado de mostrar los warnings y demás.

Parece temas de caché o ni idea, no sé lo que hay por debajo, lo que estoy seguro es que el mismo input puede dar distintos outputs (más allá de las ops/s que lógicamente es irrelevante) y a veces se puede buggea, sólo tú sabes las tripas jajaja así que es difícil saber por qué bajo determinadas circunstancias se comporta así. Ojalá sirva 🙌 .

**Comment by midudev** [comment]
Era un error de la sintaxis del `??` que hacía darte una complejidad de 1. Ahora está arreglado, por lo que es normal que de la complejidad esperada.
