### ISSUE TITLE
problema con el error de test secreto.

### ISSUE THREAD

**Issue by sefhirothxd** [midudev/adventjs-issues#225]
tengo un problema con el test secreto al enviar mi Código, ya que para cambiando de error al reenviarlo.

https://github.com/midudev/adventjs-issues/assets/61520167/d42bec4e-aa4a-4a2c-b6cb-ca9df72f0afe

**Comment by JefferGonzalez** [comment]
Hola buenas noches.

Realmente no es un error, diría que es más un típico caso de falsy values; como lo es el 0, dado que el caso secreto lo contiene.

Podrías explorar solucionándolo con la ayuda de  Nullish coalescing operator (??)

**Comment by sefhirothxd** [comment]
entiendo. gracias por la corrección ahora me queda mas claro el problema que tuve.👍
