### ISSUE TITLE
Puntuaciones sustancialmente distintas si se usa Typescript

### ISSUE THREAD

**Issue by iivvaannxx** [midudev/adventjs-issues#227]
Yo ya hice mi reto, aún asi no pude evitar la tentación de mirar el Discord y probar las mejores soluciones. Quiero hacer todos los retos usando solo TypeScript, pero no si me va a puntuar peor :(

Este código (reto 1):

```js
function findFirstRepeated (gifts) {

  return gifts.filter((item, index) => (gifts.indexOf(item) !== index))?.[0] ?? -1
}
```

da este resultado con JavaScript:

![image](https://github.com/midudev/adventjs-issues/assets/47715589/655ea897-b325-43f3-952a-e605dda50806)

y sin ni siquiera cambiar nada de código, cuando lo envias usando TypeScript, este es el resultado:

![image](https://github.com/midudev/adventjs-issues/assets/47715589/91d63d01-0bde-4b22-aca7-bf3e2461f590)

Creo que algo no anda bien... :P

**Comment by midudev** [comment]
Ya comentamos el año pasado y este en el directo que TypeScript compila el código ya que Node no tiene soporte nativo. No es que "no ande bien", es que la compilación de TypeScript de cada código puede ser un mundo. :)
