### ISSUE TITLE
Error al intentar ejecutar codigo TypeScripts

### ISSUE THREAD

**Issue by JonAnderBeroz** [midudev/adventjs-issues#234]
Hoy haciendo el reto 2 y 3 en TypeScript me salio el siguiente error:

![imagen](https://github.com/midudev/adventjs-issues/assets/53355799/a614350d-890c-4216-a299-ba209bd79d81)

El código es el siguiente:

![imagen](https://github.com/midudev/adventjs-issues/assets/53355799/6620fef4-8b96-4a18-b94c-61755883fc4d)

Este código lo estoy ejecutando desde un navegador Firefox, y a mi conocimiento el codigo presentado no deberia generar este tipo de error.

Aparte probé a ejecutar el código en RunJs y ejecuta como se espera.

**Comment by midudev** [comment]
Arreglado. Estuve haciendo unos cambios para intentar mejorar las compilaciones de TS.
