### ISSUE TITLE
Error al guardar el último código utilizado

### ISSUE THREAD

**Issue by fedeperin** [midudev/adventjs-issues#235]
Al salir de la página del segundo reto y volver a entrar, el reto vuelve a mostrarse una solución anterior. Esa no es la mejor opción, es una de las tantas que intenté, tampoco es la primera.

https://github.com/midudev/adventjs-issues/assets/83504427/e5039c5e-12f8-434a-b193-84fdf53aa1fc

**Comment by midudev** [comment]
Ni idea, siempre debería guardar la que te dio mejor puntuación. Se me ocurre que pudo ser una race condition.
