### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by VictorGugg** [midudev/adventjs-issues#237]
Can't we just have the logs available . Right now it's a bit tedious to do without it's implementation right on the website.

**Comment by midudev** [comment]
This is complicated, as it could leak some internals but I'll keep the issue around in case I found a way to get it.

**Comment by roxguel** [comment]
Hi, Midu. So why not activate it only for tests that are public?

**Comment by walterlarrea** [comment]
I'm using github's codespaces when using a slow PC at my workplace, and using the test cases on the examples.

**Comment by juanjoGonDev** [comment]
You can always use https://www.typescriptlang.org/play

**Comment by ribonuclecode** [comment]
@VictorGugg If it helps you, many of us are running in environments like RunJS or in our IDEs verifying the tests that are public and once we see that everything is ok, we upload it the solution
