### ISSUE TITLE
Diseño responsive en móvil está roto

### ISSUE THREAD

**Issue by asterismvs** [midudev/adventjs-issues#239]
Cuando entro desde el celular se pierde la consigna del reto y  también queda abajo del código un espacio vacío muerto de risa xD

![IMG_20231204_154209](https://github.com/midudev/adventjs-issues/assets/98097776/bf69e58b-d379-4a5f-bb2e-c5666ae164e4)

**Comment by midudev** [comment]
Ya está arreglado:

![CleanShot 2023-12-10 at 20 10 08@2x](https://github.com/midudev/adventjs-issues/assets/1561955/305cca75-f6e9-4487-8b8d-1d90848e8b7d)
