### ISSUE TITLE
Variación del puntaje

### ISSUE THREAD

**Issue by walterlarrea** [midudev/adventjs-issues#243]
Hice los retos 1 y 2 y obtuve un puntaje. Más tarde volví a hacer el reto n1 y como no me dio mejor puntuación, volví a pegar el código anterior y envié el código, pero esta vez me dio una puntuación diferente. Lo probé en el reto n2 y sucedió lo mismo, volví a enviarlo sin modificar el código y volvió al score anterior.

Al fin que ambos retos quedaron con la puntuación más alta que me dio en esos intentos que fueron idénticos..

**Comment by roxguel** [comment]
Me sucedió lo mismo:
Envié un reto, me dio 250 puntos, hice un pequeño cambio (de `if` a `else if`) y me dio 360 puntos. Pensé que era porque el código era más legible, pero cuando volví a enviarlo para ver la complejidad cognitiva volvió a darme 250. Volví a enviarlo (sin modificar nada) y volvió a darme 360 puntos.

Imagino que esto sucede porque evalúa el tiempo que demora el ejecutar el código, pero me parece que las variaciones son muy grande.

**Comment by midudev** [comment]
Es normal que pueda variar la puntuación por el número de operaciones por segundo, que no es fija. Igualmente la puntuación variará entre dos diferentes, no es algo ilimitado.
