### ISSUE TITLE
Error en la cantidad de retos resueltos de la tabla de Clasificación

### ISSUE THREAD

**Issue by lllariogonzalez** [midudev/adventjs-issues#244]
Luego de resetear uno de los retos, la tabla de clasificación muestra un número incorrecto de retos resueltos con relación a los actuales.

En mi caso reseteé el primer reto, actualmente los retos disponibles son 5 y en la tabla de clasificación figuran 6.
Creo que el error se debe al hecho de resetear.

![image](https://github.com/midudev/adventjs-issues/assets/101127703/20144730-7977-4a88-a71c-65e36bd107cf)

**Comment by midudev** [comment]
Ya lo tenemos arreglado.
