### ISSUE TITLE
[i18n]: challenge #2 code examples are in Spanish

### ISSUE THREAD

**Issue by genaroibc** [midudev/adventjs-issues#245]
In challenge 2, code example strings are in Spanish instead of English though you are viewing the English site
https://adventjs.dev/en/challenges/2023/2

![challenge-2](https://github.com/midudev/adventjs-issues/assets/98661193/8d4094ed-a429-4f60-95e9-7e54fb8b10aa)

**Comment by midudev** [comment]
Los ejemplos de código, a no ser que sean comentarios, no se traducen. Los ejemplos se mantienen ya que es indiferente el significado de las cadenas.
