### ISSUE TITLE
[Reto #6] Error de arrow-functions e imports/export cuando no existe

### ISSUE THREAD

**Issue by ribonuclecode** [midudev/adventjs-issues#246]
## Descripción
El servidor devuelve un error de incompatibilidad con la especificación ES2017, concretamente indica que no puedo usar imports/exports ni arrow-functions fuera de la función, **cuando no se están usando**.

## Para Reproducirlo

1. Acceder a la página de AdventJs 2023 al Reto 6 (https://adventjs.dev/es/challenges/2023/6)
2. Indicar el siguiente código cómo solución:
```javascript
function maxDistance(movements) {
  let distance = 0;
  const obj = {'>': 0, '<': 0, '*': 0};
  const f = {'>': 1, '<': -1, '*': 0};
  for (const move of movements) {
    distance+=f[move];
    obj[move]+= 1;
  }
  const f = obj['>'] > obj['<'] ? 1 : -1;
  return Math.abs(distance + obj['*'] * f);
}
```
3. Pulsar el botón de "Enviar solución"

## Comportamiento esperado
- Dar el problema cómo válido con su puntuación / error en algún test secreto

## Captura
<img width="1059" alt="captura-error" src="https://github.com/midudev/adventjs-issues/assets/16759154/c1f1c15a-2bd4-47bd-a002-e0f46c3ec9b0">

## Navegador
 Chrome

## Contexto adicional
No parece ser un problema de mi cuenta ya que me ha aceptado otras soluciones similares al mismo reto

**Comment by lllariogonzalez** [comment]
Buenas @ribonuclecode a veces el error no es muy descriptivo en la web, por temas de seguridad, pero al ver tu código veo que estás declarando 2 veces la variable f, el código tienen errores de sintaxis.

Basándome en tu lógica, esta es una posible corrección del código y solución al reto:

```javascript

function maxDistance(movements) {
  let distance = 0;
  const obj = {'>': 0, '<': 0, '*': 0};
  const f = {'>': 1, '<': -1, '*': 0};

  for (const move of movements) {
    distance += f[move];
    obj[move] += 1;
  }

  const comparison = obj['>'] > obj['<'] ? 1 : -1;
  return Math.abs(distance + obj['*'] * comparison);
}

```

**Comment by ribonuclecode** [comment]
Gracias!
