### ISSUE TITLE
Error en Reto#3 al acceder al elemento del array modified

### ISSUE THREAD

**Issue by byMagg** [midudev/adventjs-issues#248]
Probando me he dado cuenta que el test 3 puede que esté mal, si os dais cuenta para probar estoy devolviendo `modified[4]` pero en ese test supuestamente estaría fuera de rango del array pero sin embargo devuelve "e" y como correcto
![image](https://github.com/midudev/adventjs-issues/assets/44727429/63dd9dbb-57b9-49e3-83d6-d380af1fa5a8)

**Comment by juanjoGonDev** [comment]
+1 Para mi primera función (ocultada para no dar pistas) vista en la siguiente captura
![imagen](https://github.com/midudev/adventjs-issues/assets/88344734/6b9ec226-02b5-41ea-9835-e6372795293e)

El test 3 debería devolver ''. Pero devuelve 'e';
Si intento hacer un error con la condición del string original, no salta, por lo que intuyo que se le está pasando otro argumento a dicho parámetro. Siendo éste, el argumento del test 2 quizás.
![imagen](https://github.com/midudev/adventjs-issues/assets/88344734/dd45b535-cdc3-4ba9-bb75-63c7b584c850)
