### ISSUE TITLE
implementación errónea de los métodos iterativos de las matrices

### ISSUE THREAD

**Issue by codergaz** [midudev/adventjs-issues#249]
Hola,

Probando distintas soluciones para un reto he comprobado que no se soporta el parámetro thisArg para los métodos iterativos de Array. Lo cual incumple el estándar (es algo presente desde ECMAScript 5.1).

Por ejemplo, este código:

```javascript
gifts.some(
    function (g, i) {
      ...
      return this.add(g).size <= i;
    },
    new Set()
  );
```

genera el (falso) error:

> Tu código tiene errores
> Cannot access "this" object

Sería conveniente revisarlo, para evitar tener que utilizar rodeos no necesarios.

¡Y gracias por ofrecernos los retos!

**Comment by midudev** [comment]
No vamos a añadir soporte al objeto `this` en ningún caso. Así se evitan posibles ataques de forma sencilla y existen alternativas para solucionarlo.

**Comment by codergaz** [comment]
Que existen alternativas (para todo) es evidente, pero... en ese caso creo que sería necesario indicar en las FAQ (aunque no sea una consulta frecuente) que el código aceptado no corresponde exactamente al estándar ECMAscript.

¡Ánimo con los pesados (como yo)!
