### ISSUE TITLE
Ver mejores códigos en cada reto (Al finalizar el adviento)

### ISSUE THREAD

**Issue by juanjoGonDev** [midudev/adventjs-issues#251]
Mostrar el mejor código puntuado para cada reto una vez finalice el adviento. Se que se puede seguir realizando una vez finalice, en ese entonces quizás que no puntúe para la clasificación. Tengo curiosidad como se las han ingeniado para aumentar la optimización y reducir la carga cognitiva. En algunos de mis retos lo he conseguido, en otros no. 

Me gustaría aprender de las mejores soluciones

**Comment by ribonuclecode** [comment]
¡Apoyo esta moción!, me gustaría mejorar mi código existente y me gustaría ver cómo otros han pensado en sus soluciones para mejorar las mias (aunque ya no puntuen para clasificacion). Sobre todo para aprender y mejorar cómo programador.

**Comment by mamjerez** [comment]
Un voto más para implementar esta mejora.

**Comment by yasai59** [comment]
Me parece una propuesta muy interesante. Pero creo que habria que dejar un tiempo de gracia, por si los ultimos dias hay gente que no haya podido acabar los retos por las festividades.

**Comment by gtrabanco** [comment]
Otra opción puede ser ver la puntuación máxima conseguida en cada reto y no ver ningún código.

**Comment by ribonuclecode** [comment]
@gtrabanco eso es otro tema distinto al que presentamos acá. Además lo que planteas ya se comentá aca: https://github.com/midudev/adventjs-issues/issues/211 por si te interesa aportar allá tu voto u opinión para que lo implementen (a mi también me gusta esa idea)

**Comment by gtrabanco** [comment]
> @gtrabanco eso es otro tema distinto al que presentamos acá. Además lo que planteas ya se comentá aca: https://github.com/midudev/adventjs-issues/issues/211 por si te interesa aportar allá tu voto u opinión para que lo implementen (a mi también me gusta esa idea)

Gracias, no lo había visto 🫶

**Comment by ribonuclecode** [comment]
se sabe algo de esto?
