### ISSUE TITLE
RETO 7: Adventjs 2023 - Consulta sobre error del cual no conozco el motivo

### ISSUE THREAD

**Issue by leopereyrav** [midudev/adventjs-issues#252]
AL revisar el reto 7 del Adventjs 2023, me muestra que mi código no pasa varios test, pero, al comparar, el resultado esperado con el actual, se ve que son iguales. Por ello, no sé cuál sería el problema para que los tests no lo acepten.

![image](https://github.com/midudev/adventjs-issues/assets/30556710/afa7dfb7-c1be-45e6-b32b-3da7d45a6110)
![image](https://github.com/midudev/adventjs-issues/assets/30556710/c0fea7a5-6a91-45f9-af25-db3d9e5627eb)
![image](https://github.com/midudev/adventjs-issues/assets/30556710/c2c02c15-49a9-4b40-ac35-f749e32e2c68)
![image](https://github.com/midudev/adventjs-issues/assets/30556710/7ce1e173-f674-4e43-bea0-cceb10829eda)

**Comment by hakantakiri** [comment]
Estoy teniendo exactamente el mismo error

**Comment by hakantakiri** [comment]
@midudev el texto esperado por los tests es el mismo que imprimimos con nuestras funciones, para muestra el resultado de dos textos fallidos que en realidad deberían de haber pasado:
```
Test: drawGift(4, "+")

Expected:
"   ####
  #++##
 #++#+#
####++#
#++#+#
#++##
####
"

Actual:
"   ####
  #++##
 #++#+#
####++#
#++#+# 
#++##  
####   
"
```

```
Test: drawGift(10, "%")

Expected:
"         ##########
        #%%%%%%%%##
       #%%%%%%%%#%#
      #%%%%%%%%#%%#
     #%%%%%%%%#%%%#
    #%%%%%%%%#%%%%#
   #%%%%%%%%#%%%%%#
  #%%%%%%%%#%%%%%%#
 #%%%%%%%%#%%%%%%%#
##########%%%%%%%%#
#%%%%%%%%#%%%%%%%#
#%%%%%%%%#%%%%%%#
#%%%%%%%%#%%%%%#
#%%%%%%%%#%%%%#
#%%%%%%%%#%%%#
#%%%%%%%%#%%#
#%%%%%%%%#%#
#%%%%%%%%##
##########
"

Actual:
"         ##########
        #%%%%%%%%##
       #%%%%%%%%#%#
      #%%%%%%%%#%%#
     #%%%%%%%%#%%%#
    #%%%%%%%%#%%%%#
   #%%%%%%%%#%%%%%#
  #%%%%%%%%#%%%%%%#
 #%%%%%%%%#%%%%%%%#
##########%%%%%%%%#
#%%%%%%%%#%%%%%%%# 
#%%%%%%%%#%%%%%%#  
#%%%%%%%%#%%%%%#   
#%%%%%%%%#%%%%#    
#%%%%%%%%#%%%#     
#%%%%%%%%#%%#      
#%%%%%%%%#%#       
#%%%%%%%%##        
##########         
"
```

**Comment by hakantakiri** [comment]
@midudev y @leopereyrav ya descubrí el error. Las instrucciones del reto no especifican que no deben haber espacios vacíos al final de cada linea. En la mía si que estaba agregando espacios vacíos y ya logré limpiarlos. Es tu mismo caso @leopereyrav ?

**Comment by leopereyrav** [comment]
uff muy buena observación @hakantakiri. Ya lo solucioné. Muchas gracias

**Comment by ribonuclecode** [comment]
Buenas, si a alguien le sirve es exactamente lo que comentais. El problema es que el resultado final espera espacios al final de cada linea también (pero no se ven bien en la solución).
