### ISSUE TITLE
Está mal el primer ejemplo en el reto 10

### ISSUE THREAD

**Issue by fedeperin** [midudev/adventjs-issues#255]
El primer ejemplo en las instrucciones del reto 10 parecería estar mal.  
Da un ejemplo con 4 de altura y una cadena de texto "123". Dice que tendría que ser así: 
```
    1
   2 3
  1 2 3
1 2 3 1 2
    |
```
Pero en los tests se ve como la última línea no tiene esa cantidad de caracteres, se tendría que ver así:
```
    1
   2 3
  1 2 3
 1 2 3 1
    |
```

**Comment by midudev** [comment]
Fixed
