### ISSUE TITLE
La longitud de línea no se está detectando bien

### ISSUE THREAD

**Issue by joecarl** [midudev/adventjs-issues#256]
He recibido advertencias por líneas largas cuando ninguna de mis líneas superaba los 80 caracteres.
Según he podido detectar, el fallo es que aunque yo escriba código de esta manera:
```js
    if (
      originalCharCode >= 'A'.charCodeAt(0) &&
      originalCharCode <= 'Z'.charCodeAt(0) &&
      (copy[i] === original[i].toLowerCase() || degradedIndex !== -1)
    ) {
      continue;
    }
```

El programa lo interpreta como si fuera una sola línea: 
```js
    if (originalCharCode >= 'A'.charCodeAt(0) && originalCharCode <= 'Z'.charCodeAt(0) && (copy[i] === original[i].toLowerCase() || degradedIndex !== -1)) {
      continue;
    }
```

**Comment by midudev** [comment]
Es posible que estés usando TypeScript y, al compilarlo, cambia la longitud de las líneas. Por desgracia no podemos controlar el comportamiento del compilador. Lo que puedes hacer es guardar en variables los cálculos para evitarlo.

**Comment by joecarl** [comment]
En ese caso, la solución seria contar la longitud de línea antes de compilar
