### ISSUE TITLE
Un mismo código puede causar diferentes puntuaciones según el momento en que se envía

### ISSUE THREAD

**Issue by joecarl** [midudev/adventjs-issues#257]
He enviado el mismo código varias veces y hay ocasiones en las que la puntuación varía. He observado que la velocidad de ejecución es diferente cada vez (supongo que será debido a la carga del servidor), y entiendo que esta es la causa del problema.

**Comment by midudev** [comment]
Es normal. No es un problema, es que las operaciones por segundo son elásticas en cualquier sistema informático.

**Comment by joecarl** [comment]
Entiendo que no es un bug como tal, pero sí es un problema para calcular puntuaciones justas no crees?
He pensado que si se pudiera obtener el número de ciclos empleados (que debería ser siempre el mismo para un código dado), quizá podría ser una mejor alternativa para calcular una puntuación más justa. Aunque desconozco si se puede obtener ese valor.
