### ISSUE TITLE
En firefox no corre

### ISSUE THREAD

**Issue by Andres-Parra2610** [midudev/adventjs-issues#26]
Hola midu, espero estés bien. Es para notificarte que en firefox no corren los tests, se queda en "ejecutando tests...". Sólo es una observación a considerar, ya que lo probé en chrome y me corrió magnifico. Gracias por esta iniciativa!!

**Comment by midudev** [comment]
@Andres-Parra2610 me puedes pasar un código que se te quede así? A ver si puedo hacer que no pase. ¡Gracias!

**Comment by Andres-Parra2610** [comment]
@midudev tranquilo. Todo solucionado, al parecer todo se arregló hoy c:

**Comment by midudev** [comment]
:) Sí, he hecho que Firefox funcione mejor. No funciona el 100% de los casos (por ejemplo, código que pones fuera de la función) pero algo es algo. :D
