### ISSUE TITLE
Reto 2: Código funciona para todos los tests pero no para un caso de ejemplo

### ISSUE THREAD

**Issue by gustadev121** [midudev/adventjs-issues#267]
Resolviendo el ejercicio 2, coloqué este código
```javascript
function manufacture(gifts, materials) {
  const created = []
  let fl = true
  for(let gift of gifts){
    for(let c of gift){
      if(materials.indexOf(c) == -1){
        fl = false;
        break;
      }
    }
    if(fl)
      created.push(gift)
  }
  return created
}
```
La bandera (`fl`) no se actualiza adecuadamente e ignora la adición al arreglo resultante de las palabras que cumplen la condición pero se sitúan después de una palabra que no cumple la condición.  Por lo que en este ejemplo mostrado en las instrucciones del reto, el código anterior no tendría un resultado satisfactorio. Sin embargo, todos los tests fueron correctos al ejecutarlo
```javascript
const gifts = ['juego', 'puzzle']
const materials = 'jlepuz'
manufacture(gifts, materials) // ["puzzle"]
```
![advent-issue](https://github.com/midudev/adventjs-issues/assets/147654561/40b6a335-8694-475d-8a8d-9c83031b7e28)

Sugiero añadir tests que consideren casos como el del ejemplo anterior.

**Comment by gusCreator** [comment]
Subo la imagen del resultado al enviar el código (ayer no dejaba subir)
![Resultado al enviar el código](https://github.com/midudev/adventjs-issues/assets/147654561/b0a0f89d-84fc-4e5d-b176-ff29618ccce3)
