### ISSUE TITLE
Deslineamiento de elementos de los nav del Header

### ISSUE THREAD

**Issue by rr69sport** [midudev/adventjs-issues#269]
Hay un pequeño desalineamiento entre elementos del Header. Adjunto fotos para ser más explícito y no alargar tanto la issue.

Este sería el desalineamiento que he notado.
![image](https://github.com/user-attachments/assets/03644d6d-f408-47ed-86db-3458c51d8f10)

Generado por una margin en este elemento.
![Captura de pantalla 2024-11-28 150748](https://github.com/user-attachments/assets/57e8fb39-64f1-491d-9f28-dd69911fcca3)

Así se vería ya corregido. (Cabe destacar que están pegados al borde arriba para que se note la diferencia.
![Captura de pantalla 2024-11-28 150635corregido](https://github.com/user-attachments/assets/884ef221-db10-4f65-a604-7c04dd7ec2f0)

**Comment by midudev** [comment]
Creo qua ya lo tenemos arreglado. Gracias!

**Comment by rr69sport** [comment]
> Creo qua ya lo tenemos arreglado. Gracias!

Es un placer :)
