### ISSUE TITLE
Popup de revisión de código algo intrusivo

### ISSUE THREAD

**Issue by alvarolozano** [midudev/adventjs-issues#27]
Durante la edición de código, se realizan los tests automáticamente mientras se escribe, lo que provoca que en algunos casos no se vea el código que se está escribiendo.

Se me ocurre que en vez de posicionar el mensaje sobre el contenedor del editor, se haga en la parte inferior de la página, de manera similar a los "toast" de Android.

Adjunto captura de ejemplo:

![image](https://user-images.githubusercontent.com/10405074/144431879-44b9f7e1-3b96-4d11-8dd5-bbfd52e23179.png)

**Comment by midudev** [comment]
Se ha movido debajo del editor.
