### ISSUE TITLE
Duplicated FAQ under 1020px resolution

### ISSUE THREAD

**Issue by olaracode** [midudev/adventjs-issues#270]
![Screenshot 2024-11-28 at 3 06 54 PM](https://github.com/user-attachments/assets/ccdc501c-620d-419a-b91c-380418217865)

**Comment by josanri** [comment]
It seems it begins at 1024px (Tailwind lg), could be solved by hidding the second container with `max-lg:hidden` or by switching the classes in order to get the same style:
![image](https://github.com/user-attachments/assets/ab544c11-0235-497b-ac6c-3482ca7f6149 "HTML node with max-lg:hidden added")

**Comment by midudev** [comment]
Arreglado!
