### ISSUE TITLE
Challange3: Los test no son suficientemente intensos como para premiar soluciones escalables usando Pandas

### ISSUE THREAD

**Issue by e-duard2** [midudev/adventjs-issues#282]
He estado trabajando en el desafío **"Organizar el Inventario"** y he encontrado una solución utilizando **Pandas**, que es ampliamente usada en proyectos de **ingeniería de datos** y **ciencia de datos**, sé que a lo mejor era un poco overkill, pero pensé que sería una forma original y elegante de solucionar el problema. Aunque mi implementación pasa todos los tests, solo se me ha otorgado una estrella, probablemente porque la solución no sigue el enfoque "básico" esperado.

Sin embargo, quiero argumentar que mi solución es más **robusta** y **escalable**, especialmente en escenarios con grandes volúmenes de datos, que es un caso de uso muy común en entornos reales de **procesamiento de datos**.

## Razón del cambio

- **Escalabilidad**: Si bien la solución básica con diccionarios y bucles puede funcionar para pequeños conjuntos de datos, **Pandas** está diseñado para manejar eficientemente grandes volúmenes de datos.
- **Eficiencia**: Las operaciones de agrupación y agregación en **Pandas** son altamente optimizadas y pueden procesar datos significativamente más rápido que los bucles tradicionales en Python.
- **Adoptado en ciencia de datos**: **Pandas** es una herramienta estándar en proyectos de **Data Science** y **Machine Learning**, por lo que su uso es una **mejor práctica** en entornos donde el volumen de datos puede ser considerable.

## Mi propuesta de código

Aquí está mi solución utilizando **Pandas**:
```python
import pandas as pd

def organize_inventory(inventory):
    if not inventory:
        return {}
    
    # Convertimos la lista de diccionarios a un DataFrame
    df = pd.DataFrame(inventory)
    
    # Agrupamos por categoría y nombre, sumando las cantidades
    grouped = df.groupby(['category', 'name'])['quantity'].sum().reset_index()
    
    # Transformamos el resultado en un diccionario anidado
    result = (
        grouped.pivot(index='category', columns='name', values='quantity')
        .fillna(0)
        .astype(int)
        .to_dict(orient='index')
    )
    
    return {category: dict(items) for category, items in result.items()}
```
## Conclusión

Creo que el conjunto de tests actual podría no estar evaluando escenarios con grandes volúmenes de datos, donde la solución con Pandas destacaría. Sería interesante considerar la posibilidad de incluir pruebas adicionales para validar soluciones que prioricen la escalabilidad y el rendimiento en entornos reales.

**Comment by EverStarck** [comment]
creo que la idea de este tipo de plataformas, como leetcode, hackerrank, advent of code etc, la idea es reforzar conocimiento y aprender estructuras de datos y algoritmos, no librerias

**Comment by e-duard2** [comment]
Entiendo tu punto, pero creo que estás viendo las cosas desde una perspectiva demasiado cerrada. No todo es escribir estructuras de datos y algoritmos "desde cero". En el mundo real, **DataFrames son también estructuras de datos**, diseñadas específicamente para manipular y procesar grandes volúmenes de información de forma eficiente. Usar Pandas no es hacer trampa; es aplicar la herramienta adecuada al problema, como usaríamos un diccionario en vez de listas anidadas. No estamos programando en ensamblador por una razón: **la ingeniería evoluciona para ser más eficiente**. Reinventar la rueda está bien para aprender, pero también hay que saber cuándo usar soluciones optimizadas. 😉

**Comment by midudev** [comment]
Como dice @EverStarck el objetivo de esta plataforma no es ese. Pero puedes usar los retos para practicar como quieras fuera de ella. ¡Saludos!
