### ISSUE TITLE
Application error: a client-side exception

### ISSUE THREAD

**Issue by Mydherin** [midudev/adventjs-issues#286]
Estoy obteniendo el siguiente problema tras enviar un reto y tener un resultado exitoso.

![imagen](https://github.com/user-attachments/assets/5050b839-da63-45a2-a8ef-58201842bced)

Se llega a ver la animación de los confetis pero me aparece esta pantalla. El verdadero problema es que el resultado no se llega a guardar en mi cuenta.

Llevo hecho 4 retos y no había estado teniendo este problema. Ahora lo tengo en cada validación. El problema a comenzado a aparecer cuando me he puesto a hacer los retos con los 3 lenguajes (Como primera opción siempre uso JS).

Logs:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at K ([id]-9abeb666f050960d.js:1:36134)
    at af (framework-898697981b1ca118.js:1:58510)
    at i (framework-898697981b1ca118.js:1:119481)
    at oF (framework-898697981b1ca118.js:1:99134)
    at framework-898697981b1ca118.js:1:99001
    at oM (framework-898697981b1ca118.js:1:99008)
    at oS (framework-898697981b1ca118.js:1:95760)
    at ow (framework-898697981b1ca118.js:1:94315)
    at x (framework-898697981b1ca118.js:1:137489)
```

**Comment by Mydherin** [comment]
Uso Brave pero también soy capaz de reproducirlo en firefox

**Comment by grisendo** [comment]
En chrome también

**Comment by grisendo** [comment]
Acabo de probar y en mi caso solo me ocurre en el reto 2 en typescript

**Comment by e-duard2** [comment]
también en mi caso usando Python y Firefox _"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:133.0) Gecko/20100101 Firefox/133.0"_

**Comment by midudev** [comment]
¿Podéis probar ahora?

**Comment by e-duard2** [comment]
@midudev Parece que ahora no se cuelga, lo único que me he dado cuenta que en el ejercicio pone que tengo 5 estrellas pero en el calendario global me da 3.

Update: antes de publicar esto me ha dado por probar el responsive y era esto, que la campana tapa algunas estrellas. a lo mejor un z index lo soluciona rápido (aunque quedaría feo) mejor un padding o margin

**Comment by midudev** [comment]
Perfecto, gracias por revisar. :)
