### ISSUE TITLE
Idioma no se mantiene en la página 404

### ISSUE THREAD

**Issue by christopher-dev-91** [midudev/adventjs-issues#288]
Cuando vas a una página que no exista (como un reto que aún no está publicado), la página de 404 mete por defecto el idioma inglés, sin tener en cuenta tu idioma seleccionado.

![image](https://github.com/user-attachments/assets/e0c5060d-c911-4b4c-b847-c606f1ebd8ad)
![image](https://github.com/user-attachments/assets/78accd0e-35ba-4d67-a464-43e9e556dee1)

**Comment by josanri** [comment]
Creo que este `issue` está duplicado: https://github.com/midudev/adventjs-issues/issues/273
