### ISSUE TITLE
bug: logo incompleto en algunas dimensiones

### ISSUE THREAD

**Issue by josanri** [midudev/adventjs-issues#289]
En el nodo:
```html
<img src="/logo.webp" alt="logo" class="object-cover w-auto h-12">
```

, la altura (`height: 3 rem`) ocasiona para algunos casos el siguiente bug visual:

![image](https://github.com/user-attachments/assets/840b664c-584b-47b7-a0eb-f1a396269a25 "Logo con clase css h-12")

Cambiándolo a `max-h-12` la regla no es tan estricta e impide ese error:

![image](https://github.com/user-attachments/assets/454e73be-53c9-44cd-a60e-38c84ea45103 "Logo con clase css max-h-12")

PD: El texto alternativo como logo pudiera ser mejor con otro nombre más indicativo (Go home)

**Comment by midudev** [comment]
¡Arreglado!
