### ISSUE TITLE
Mantener el código

### ISSUE THREAD

**Issue by jasba24** [midudev/adventjs-issues#29]
Me gustaria que mientras se desarrolla un reto al refrescar la pagina el código se mantuviera y no se borrara como en https://codi.link/

**Comment by midudev** [comment]
Repetido: https://github.com/midudev/adventjs-issues/issues/3

**Comment by jasba24** [comment]
Con esta issue no me referia a poder ver las soluciones que se envian, si no a que cuando se esta trabajando en una solucion mientras se escribe el codigo al refrescar la pagina no se borre todo lo que se escribio antes de enviarse.
Dejo un gif de referencia 
![test](https://user-images.githubusercontent.com/71221550/145469213-c1ddac5b-8cbb-46ec-ae3e-9a3a27f53a3a.gif)
