### ISSUE TITLE
El challange 5 no se encuentra activo

### ISSUE THREAD

**Issue by e-duard2** [midudev/adventjs-issues#292]
@midudev , sé que es muy tarde hehehehe pero me he liado haciendo cosillas y me ha dado por ir a ver el challange 5 antes de irme a la cama y no se encuentra abierto.

**Comment by midudev** [comment]
Hola Eduard, estoy en Chile y por el cambio de hora se demoró pero ya está activo.

**Comment by e-duard2** [comment]
@midudev Gracias! Pensé que era automático. Por eso el ticket.

De todos modos, ¿Por qué no haces un crontab y automatizas el proceso para que cada día se abra el challange a las 00:00? Te ahorrarías tener que pensar en ello.
