### ISSUE TITLE
La solución en este caso es incorrecta

### ISSUE THREAD

**Issue by andresGarcia90** [midudev/adventjs-issues#294]
const shoes3 = [
  { type: 'I', size: 38 },
  { type: 'R', size: 36 },
  { type: 'R', size: 42 },
  { type: 'I', size: 41 },
  { type: 'I', size: 42 }
]

organizeShoes(shoes3)
// []

Debería retornar 
[42]

**Comment by midudev** [comment]
Typo pero los tests estaban bien. Gracias!
