### ISSUE TITLE
Error al mostrar "Logros básicos"

### ISSUE THREAD

**Issue by alejandro-dev** [midudev/adventjs-issues#295]
Tengo completado los primeros 5 retos con JS como con TS pero solo me aparece que tengo completado los de JS.
<img width="1133" alt="Captura de pantalla 2024-12-05 a las 9 31 19" src="https://github.com/user-attachments/assets/6e9984ac-0d34-4bda-913b-3796effb2bbf">

**Comment by midudev** [comment]
Ya está arreglado. Vuelve a enviar un reto de TypeScript y se desbloqueará.
