### ISSUE TITLE
 No puedo enviar mi solución al reto 2 de AdventJS

### ISSUE THREAD

**Issue by Pedro5657** [midudev/adventjs-issues#298]
¡Hola Midu!

Estoy haciendo tu (guapísimo) reto navideño. He terminado el ejercicio del segundo día y, aunque la solución se ejecuta adecuadamente en mi terminal y parece ser correcta, no puedo evaluarla.

![Screenshot 2024-12-05 140201](https://github.com/user-attachments/assets/41485355-8b0c-4f9a-8aeb-0e9a9425c80b)

Aquí te dejo un screenshot por si te ayuda. ¡Muchas gracias!

**Comment by midudev** [comment]
¡Prueba ahora! 👍

**Comment by Pedro5657** [comment]
¡Mil gracias!
