### ISSUE TITLE
Guardar el estado del código por si vuelve el usuario

### ISSUE THREAD

**Issue by midudev** [midudev/adventjs-issues#3]
El código que el usuario añade en el editor no se guarda y, si se va, entonces se pierde y tiene que empezar desde cero. Hay que buscar una forma que esto se guarde.

**Comment by manudefrutosvila** [comment]
Además serviría para los retos ya enviados. Para poder recuperar tus soluciones y para compararla con otras soluciones de la comunidad

**Comment by s3iken** [comment]
a
