### ISSUE TITLE
[Error] la seccion de python valida codigo javascript

### ISSUE THREAD

**Issue by cesar-aguirre-yalo** [midudev/adventjs-issues#301]
se puede enviar el codigo como este en la solucion de js en la seccion de python y lo valida como correcto

![image](https://github.com/user-attachments/assets/6f4723e6-a256-4f35-bbca-5ca2248c9576)
![image](https://github.com/user-attachments/assets/93c37d4b-110a-4e92-8f94-74fbd5bf958a)

**Comment by CesarDavidAguirre** [comment]
lo cerre porque no me di cuenta y abri el issue con la cuenta del trabajo xD
