### ISSUE TITLE
bug en casos de prueba del reto 6 python

### ISSUE THREAD

**Issue by jdelarubia** [midudev/adventjs-issues#303]
Según las instrucciones, el regalo debe estar totalmente rodeado por el carácter `#` 
```
The box has a present (*) and counts as "inside the box" if:

- It is completely surrounded by # on the box's edges.
- The * is not on the box's edges.
```
![2024-12-06-screenshot](https://github.com/user-attachments/assets/06ac5f1b-5d09-4717-a6ba-052cd8ac1b4d)

Los casos de prueba 6, 8, 9, 10 y 11 no respetan esta premisa.

**Comment by jdelarubia** [comment]
Definitivamente, no hay forma de superar los tests.

Aquí dejo el enlace al [código completo con tests manuales](https://github.com/jdelarubia/adventjs_dev/blob/main/06advent.py)

**Comment by fernandezguille** [comment]
Leí en otra issue que el problema es con #. Yo cambié por "\u0023" y me funcionó bien

**Comment by jdelarubia** [comment]
Pues se ha solucionado con este cambio, pero ni idea de por qué ocurre. Muchas gracias @fernandezguille !
