### ISSUE TITLE
Problems with hash character in Python

### ISSUE THREAD

**Issue by mrey-profe** [midudev/adventjs-issues#304]
Congratulations for the calendar, I'm really enjoying it.
I am trying to solve it in Python and I find trouble each time I have to compare something with # character. For example, on day 6 challenge I had to compare it with \u0023 instead of '#' in order for it to pass the tests.

**Comment by jdelarubia** [comment]
> Congratulations for the calendar, I'm really enjoying it. I am trying to solve it in Python and I find trouble each time I have to compare something with # character. For example, on day 6 challenge I had to compare it with \u0023 instead of '#' in order for it to pass the tests.

Are you maybe copying and pasting your code in the editor? Check the encoding of your file from which you are copying it from.
I can run the comparissons without problems, `"#" == character`..., although there seem to be some issues with the tests (perhaps on my side).

**Comment by fernandezguille** [comment]
> Congratulations for the calendar, I'm really enjoying it. I am trying to solve it in Python and I find trouble each time I have to compare something with # character. For example, on day 6 challenge I had to compare it with \u0023 instead of '#' in order for it to pass the tests.

Thanks for the tip! I was having the same issue, it solved using "\u0023"

**Comment by midudev** [comment]
Fixed!
