### ISSUE TITLE
Error 500 en "Trofeos"

### ISSUE THREAD

**Issue by IscMiguelAngel** [midudev/adventjs-issues#306]
Al hacer clic en la pestaña trofeso, la ventana muestra un error de servidor.

Link: [Logros](https://adventjs.dev/es/achievements)

![Captura de pantalla 2024-12-06 143748](https://github.com/user-attachments/assets/2e0300ff-4ecf-4a18-8de3-917a5eb0ec8d)

**Comment by midudev** [comment]
¡Hola! Por desgracia, con la información que proporcionas es imposible tomar ninguna acción. ¿Estabas con la sesión iniciada? ¿Tenías algún logro? ¿Te ha funcionado alguna vez? ¿Sale algo en consola como error?

Si puedes, crea otra issue con la máxima información. Gracias!
