### ISSUE TITLE
Reto #6: Nombre del parámetro de la función no coincide con la documentación. Lenguaje Javascript

### ISSUE THREAD

**Issue by ansecede** [midudev/adventjs-issues#309]
La documentación de la función inBox utiliza como nombre del parámetro **_gifts_**, pero en la firma de la función el parámetro se llama **_box_**. Es una pequeña discrepancia que causa que el parámetro tenga tipo _any_ y por tanto el autocompletado no funciona.
![image](https://github.com/user-attachments/assets/ded838b9-23cc-4b9d-96b0-564c3c3595f9)

**Comment by midudev** [comment]
Fixed!
