### ISSUE TITLE
Opción de submit

### ISSUE THREAD

**Issue by emquiroga** [midudev/adventjs-issues#31]
Hola Midu, cómo estás? Espero que muy bien. Me gustaría sugerir que implementaces un método de submit y de correción post submit como alternativa a la revisión en vivo. He encontrado un poco molesta esta última. En todo caso, el alert del lintern debería estar por fuera de la ventana del Live IDE, no dentro. Tal vez te guste revisarlo. Gracias por tu aporte, espero mi consejo sirva! Un abrazo desde Argentina.

**Comment by midudev** [comment]
Ya he movido el test debajo del editor.
