### ISSUE TITLE
TypeError: " ".join is not a function # Reto 8

### ISSUE THREAD

**Issue by JuanPerdomo00** [midudev/adventjs-issues#313]
![imagen](https://github.com/user-attachments/assets/9d21fcbc-be0b-453a-bc6a-13c87c14f442)

No me deja corrar los test, dice que join no es una funcion.

**Comment by Whiskoder** [comment]
Lo pusiste con la siguiente sintaxis `<separador>.join(<iterable>)` ?

**Comment by midudev** [comment]
@JuanPerdomo00 por favor, crea la issue de nuevo pero indicando el código que no funciona, ya que así es imposible saber cuál puede ser el problema.
