### ISSUE TITLE
"Completed by" counter not working correctly sometimes?

### ISSUE THREAD

**Issue by personalyisus** [midudev/adventjs-issues#314]
Am I tripping? whenever I submit the same successful solution to a challenge it appears that the "completed by" counter is increased

I don't think a new unique user solution is added each second, otherwise the challenges would have an insane amount of completions by now

This is a recording of me submitting a solution for challenge 7 several times and the counter keeps increasing by one every time

https://github.com/user-attachments/assets/ca03a579-672c-4df6-8423-f081d9937385

Tried refreshing the page and couldn't reproduce it afterwards, but this is the second time it happens to me; maybe it's worth checking it out 👀 ?

**Comment by personalyisus** [comment]
It definitely happens some times! it seems after refreshing the page the count gets set to the correct number but every correct submission increases the counter on the clientside even though it shouldn't count

Not a big issue if the actual stats aren't affected, but yeah, small bug with the counter


https://github.com/user-attachments/assets/a401ed4e-effc-4caf-a3ae-19da1c5243bf

**Comment by maadeval** [comment]
Fixed! Thanks for reporting it 💪

@midudev ready to close
