### ISSUE TITLE
Reto 9 - Ejemplo confuso

### ISSUE THREAD

**Issue by Whiskoder** [midudev/adventjs-issues#315]
En el ejemplo, la propiedad `board` aparece de la siguiente manera y es un poco confuso de entender:

```ts

const board = ['·····', '*····', '@····', 'o····', 'o····']

...
```

De ser posible, creo que debería estar formateado en varias lineas para mejor legibilidad:

```ts

const board = [
  "·····",
  "*····",
  "@····",
  "o····",
  "o····"
]

...
```

**Comment by midudev** [comment]
Hecho!
