### ISSUE TITLE
Reto #9 desarrollado con TS

### ISSUE THREAD

**Issue by xMojica** [midudev/adventjs-issues#318]
Buenas tardes,

Mi nombre es Santiago Mojica, quisiera dar una sugerencia o corrección en el Reto # 9.

El ejemplo es:

const board = ['·····', '*····', '@····', 'o····', 'o····']
console.log(moveTrain(board, 'U'))

pero presenta un error debido a que Board es un array de Space, pero Space solo permite un caracter no una cadena de caracteres.

Mi sugerencia es que en el ejemplo coloquen:

const board: Board = [
  "·", "·", "·", "·", "·",
  "*", "·", "·", "·", "·",
  "@", "·", "·", "·", "·",
  "o", "·", "·", "·", "·",
  "o", "·", "·", "·", "·"
];

o se cambie el tipo de Board, que no sea un array de Space sino un Array de String.

type Space = '·' | '@' | '*' | 'o'
type Board = Space[]
type Movement = 'U' | 'D' | 'R' | 'L'
type Result = 'none' | 'crash' | 'eat'

function moveTrain(board: Board, mov: Movement): Result {
  // Code here
  return 'none';
}

De antemano muchas gracias Midudev por aportar a la comunidad.

**Comment by midudev** [comment]
He cambiado el type para que sea un array de strings.
