### ISSUE TITLE
Recomendación visual: Implementar View Transitions.

### ISSUE THREAD

**Issue by 20essentials** [midudev/adventjs-issues#319]
Les comparto algunos ejemplos de **View Transitions**:

1. **View Transition con Blur**  
   [GitHub Project 000-348](https://github.com/20essentials/project-000-348)

2. **View Transition con `clip-path: ellipse()`**  
   [GitHub Project 000-346](https://github.com/20essentials/project-000-346)

3. **View Transition con `clip-path: polygon`**  
   [GitHub Project 000-337](https://github.com/20essentials/project-000-337)

4. **View Transition con `hue-rotate`**  
   [GitHub Project 000-335](https://github.com/20essentials/project-000-335)

## Documentación adicional

- **Manzdev Doc**: [¿Qué son las View Transitions?](https://lenguajecss.com/animaciones/view-transition/que-son/)

**Comment by midudev** [comment]
Gracias pero ahora mismo no veo que aporte mucho. :)
