### ISSUE TITLE
Mostrar los test que fallaron

### ISSUE THREAD

**Issue by GuillermoParedes** [midudev/adventjs-issues#32]
Hola @midudev 👋
Estaba realizando el segundo ejercicio que es "Ayuda al Elfo...", tengo una solución pero me marca, error.
Mostrar los test que fallaron ayudarían para encontrar la solución optima..

```javascript
function listGifts(letter) {
 const data = letter.split(' ').reduce((prev, curr) => {
   if(!curr.startsWith('_')) {
        prev[curr] = (prev[curr] || 0) + 1
   }
   return prev;
 }, {});
 return data
}
```

![image](https://user-images.githubusercontent.com/8008841/144450591-346fed5f-f5e3-482d-815a-d08d5240d9f3.png)

**Comment by matiasdm2020** [comment]
> Hola @midudev wave Estaba realizando el segundo ejercicio que es "Ayuda al Elfo...", tengo una solución pero me marca, error. Mostrar los test que fallaron ayudarían para encontrar la solución optima..
> 
> ```js
> function listGifts(letter) {
>  const data = letter.split(' ').reduce((prev, curr) => {
>    if(!curr.startsWith('_')) {
>         prev[curr] = (prev[curr] || 0) + 1
>    }
>    return prev;
>  }, {});
>  return data
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/8008841/144450591-346fed5f-f5e3-482d-815a-d08d5240d9f3.png)

Me pasa lo mismo, y creo que es por el acento de "balón", como no se puede ver que test falla no tenes manera de orientarte

**Comment by midudev** [comment]
Es porque no estáis teniendo en cuenta que en la carta puede haber dos espacios... :P

**Comment by iRyzor** [comment]
> Es porque no estáis teniendo en cuenta que en la carta puede haber dos espacios... :P

Yo los estoy tomando en cuenta pero parece que me quieren obligar a utilizar trim, es como si se fijaran más en la forma en como se soluciona el problema a que el resultado de lo que piden.

`function listGifts(letter) {
  return letter.split(/\s+/).reduce((prev, acc) => {
    if (!acc.includes("_")) prev[acc] = prev[acc] ? ++prev[acc] : 1;
    return prev;
  }, {});
}`

![image](https://user-images.githubusercontent.com/8194839/144475687-ff300f82-94bd-4da7-9980-d9c44413bb36.png)

**Comment by GuillermoParedes** [comment]
Ahora realice el cambio para que la cadena aunque tenga n espacios, me los separe correctamente
![image](https://user-images.githubusercontent.com/8008841/144489123-0f00ad96-2e5e-4366-8222-1c70816b8888.png)


Mi codigo
```javascript
function listGifts(letter) {
 const data = letter.split(/[\s,]+/gi).reduce((prev, curr) => {
   if(!curr.startsWith('_')) {
        prev[curr] = (prev[curr] || 0) + 1
   }
   console.log(prev);
   return prev;
 }, {})
 return data
}
```
![image](https://user-images.githubusercontent.com/8008841/144488865-2f814779-4ed8-4c8d-ba71-7c0da81f239b.png)

**Comment by DanSalazar** [comment]
Midu de por si coloca la solución, con trim antes del split, quitas los dos espacios

**Comment by MarcoRodasW** [comment]
Estoy de acuerdo con lo de mostrar los tests que fallaste, sería una mejor manera para encontrar la respuesta correcta.

**Comment by midudev** [comment]
> Ahora realice el cambio para que la cadena aunque tenga n espacios, me los separe correctamente ![image](https://user-images.githubusercontent.com/8008841/144489123-0f00ad96-2e5e-4366-8222-1c70816b8888.png)
> 
> Mi codigo
> 
> ```js
> function listGifts(letter) {
>  const data = letter.split(/[\s,]+/gi).reduce((prev, curr) => {
>    if(!curr.startsWith('_')) {
>         prev[curr] = (prev[curr] || 0) + 1
>    }
>    console.log(prev);
>    return prev;
>  }, {})
>  return data
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/8008841/144488865-2f814779-4ed8-4c8d-ba71-7c0da81f239b.png)

Prueba con esta carta: `_bici _ a m __ b c a b c ` y verás que estás contando un espacio.

Sé que a veces parece que no funcionan los tests y puede haber falsos positivos (código mal que sí pasa) pero... si no pasa... es que seguramente está mal la solución por bien que parezca. 😆

**Comment by GuillermoParedes** [comment]
gracias @midudev ejercicio 2, resuelto 
![image](https://user-images.githubusercontent.com/8008841/144517292-ded88013-25ea-490d-9da9-9f059740fc0d.png)

aqui va mi solucion 

```javascript
function listGifts(letter) {
 const data = letter.trim().split(/[\s,]+/gi).reduce((prev, curr) => {
   if(!curr.startsWith('_')) {
        prev[curr] = (prev[curr] || 0) + 1
   }
   console.log(prev);
   return prev;
 }, {})
 return data
}
```

**Comment by Bayzon88** [comment]
No encuentro donde esta el error en mi codigo, en teoria con el trim estoy eliminando espacios y generando el objeto correctamente. 

```export default function listGifts(letter) {
const carta = "bici coche balón _playstation bici coche peluche";
  let cartaArray = carta.trim().split(/[\s,]+/gi);
  
  const cartaRevisada = cartaArray.filter((regalo) => {
    return regalo.search("_") < 0 ;
  });
  const contarRegalos = {};
  cartaRevisada.forEach((regalo) => {
    contarRegalos[regalo] = (contarRegalos[regalo] || 0) + 1;
  });
  return contarRegalos;
}```

**Comment by davorpa** [comment]
Algo un poquito más elegante, semántico y usando funciones puras (HOFs) :wink:

```js
function listGifts(letter) {
    letter = letter && letter.trim();
    return letter.length && letter
        .split(giftDelimiterRegex)
        .filter(matchesAll(
            negate(isStrikethrough()),
            negate(isBlank())
        ))
        .reduce(groupCounting(), {}) || {};
}

const giftDelimiterRegex = /[\s\.,:;]+/ig;

const isStrikethrough = ({mark = "_"} = {}) =>
    value => value.startsWith(mark);

const isBlank = _ => value => !value || !!value.trim();

// **** Generic Functional HOFs **** //

const matchesAll = (...predicates) =>
    (value, index, iterable) => {
        for (const predicate of predicates) {
            if (!predicate(value, index, iterable)) return false;
        }
        return !!predicates.length;
    };

const matchesAny = (...predicates) =>
    (value, index, iterable) => {
        for (const predicate of predicates) {
            if (predicate(value, index, iterable)) return true;
        }
        return false;
    };

const negate = predicate =>
    (value, index, iterable) => !predicate(value, index, iterable);

const groupCounting = ({caseInsensitive = false} = {}) =>
    (acc, value) => (acc[value] = (acc[value] || 0) + 1, acc);

```

**Comment by D-Arturo** [comment]
Buenas! No soy capaz de ver dónde está el fallo en mi lógica. Cualquier ayuda es bienvenida.

```
function listGifts(letter){
  const listaTrim = lista.trim(letter);
  const listaSplit = listaTrim.split(/[\s]+/g);
  const listaFilter = listaSplit.filter(item => item.charAt(0)!=="_");
  let listaFormateada = {};
  for(const regalo of listaFilter){
    if(!listaFormateada.[regalo]) {
      listaFormateada.[regalo] = 1;      
    } else {
      listaFormateada.[regalo] += listaFormateada.[regalo];
    }   
  }
  return listaFormateada  
}
```

**Comment by GuillermoParedes** [comment]
```javascript
      listaFormateada.[regalo] += listaFormateada.[regalo];
```
en esta linea, estas agregando el valor y no sumandole +1 por regalo.

**Comment by davorpa** [comment]
> (!listaFormateada.[regalo]

@D-Arturo, la sintaxis de indexacion es `obj[key]` sin el punto intermedio.

**Comment by midudev** [comment]
Para dudas sobre códigos, mejor usar Discord:
https://discord.com/channels/741237973663612969/915910832259477534
