### ISSUE TITLE
Resultado test#5 no lo muestra

### ISSUE THREAD

**Issue by jsteven96** [midudev/adventjs-issues#321]
Hola, muy buenas tardes.

Estaba resolviendo el problema del día 10 del calendario de Adviento, tengo una solución que parece prometedora. Envío mi resultado y me fallan en dos test. Uno de ellos es secreto por lo que sé que no puedo observarlo, pero el otro es normal (El número 5) y no puedo ver el detalle para poder hacer la corrección en mi código. Adjunto un video de réplica, espero sea algo mínimo. Por ahora lo intentaré resolver con python o javascript, pero si se me hace extraño el comportamiento...

https://go.screenpal.com/watch/cZl6YjnnwHp

**Comment by jsteven96** [comment]
Ya vi que era lo que me faltaba, en lugar de retornar un 0 retornar un undefined. De todas formas lo dejo para revisar por que sigue sin poderse ver el resultado del Test#5 🙈

**Comment by midudev** [comment]
Ya está arreglado. ¡Gracias!
