### ISSUE TITLE
Reto 8: resultado esperado erróneo en los ejemplos (error visual)

### ISSUE THREAD

**Issue by lejito** [midudev/adventjs-issues#325]
En el **Reto 8: La carrera de renos** hay un error en la sección de **instrucciones**. El ejemplo número 3 dice esto:

```ts
//  ... ejemplos anteriores

drawRace([3, 7, -2], 12)
/*
  ~~~r~~~~~~~~ /1
 ~~~~~~~~r~~~ /2
~~~~~~~~~~r~ /3
*/
```

El resultado esperado mostrado es incorrecto porque el **carril 2** debería ser `~~~~~~~r~~~~`, con la `r` un índice más atrás debido a que corresponde al índice `7`, no `8`.

Nótese que el error es solo en la visualización del ejemplo (sin embargo, podría crear confusiones al interpretar el reto), porque al hacer el test de ese caso con una solución acertada, pasa correctamente y el resultado esperado mostrado es el correcto:

![image](https://github.com/user-attachments/assets/f6c6048a-e3e9-4c24-a5af-402a45f7a255)

**Comment by midudev** [comment]
Gracias, arreglado!
