### ISSUE TITLE
Idioma no consistente

### ISSUE THREAD

**Issue by ElegantCatterpillar** [midudev/adventjs-issues#326]
Si ingresas realizando clic desde el cuadro de los retos resumidos no respeta el idioma que tienes la página, toma por default el Ingles

![image](https://github.com/user-attachments/assets/c5f22c10-a402-44da-8cac-c36708b8db8e)

**Comment by maadeval** [comment]
Solucionado! Gracias por avisar 😁 

@midudev lista para cerrar
