### ISSUE TITLE
Mostrar ejemplos de otros test para corregir fallos.

### ISSUE THREAD

**Issue by Rafa-Gayoso** [midudev/adventjs-issues#33]
Hola Midu. Ante todo, muchas gracias por esta gran iniciativa que nos ayuda a mejorar y practicar nuestros conocimientos sobre programación y JavaScript. Mi sugerencia es que podrían mostrarse otros ejemplos de test para poder corregir fallos en nuestros códigos. He probado con dos soluciones y juegos de datos distintos y no encuentro que fallo podría tener. Adjunto ejemplo del código y los juegos de datos.                                    
![code1](https://user-images.githubusercontent.com/52751451/144455685-577b601c-53b4-4cad-9d3a-f797e544bb58.png)
![code2](https://user-images.githubusercontent.com/52751451/144455706-2b614dd3-8b95-4770-9b29-60bf43fd8d40.png)

**Comment by DamianCabrio** [comment]
A mí me pasaba lo mismo, pero me di cuenta de que ese regex solamente quito los espacios entre las palabras, entonces si por ejemplo hubiera algún espacio al principio del string, estos no se eliminarían. 
Teniendo eso en cuenta lo pude solucionar.

**Comment by equiman** [comment]
ponele un `console.table(gifts)` antes del return y vas a poder ver el resultado de tu objeto y de los otros test en la consola de herramientas de desarrollo.

![image](https://user-images.githubusercontent.com/933393/144464470-ccb72c85-1cf8-4a45-91d9-91586ac42039.png)

Si queres ver la lista de entrada el pones un `consol.log` a letter.

**Comment by Rafa-Gayoso** [comment]
> A mí me pasaba lo mismo, pero me di cuenta de que ese regex solamente quito los espacios entre las palabras, entonces si por ejemplo hubiera algún espacio al principio del string, estos no se eliminarían. Teniendo eso en cuenta lo pude solucionar.

Gracias. Probaré con esta sugerencia. Muchísimas gracias!

**Comment by silverbryan** [comment]
@Rafagayoso1997  esta perfecta tu expresion regular, pero ten en cuenta que el string puede contener espacios en el principio por lo cual al hacer un replace se añade un # al principio de la cadena, luego el split toma el primer elemento como vacio, pero estas muy cerca te falta una comprobacion, un saludo!

![image](https://user-images.githubusercontent.com/50382234/144476007-4eaa116a-e7cd-46bb-aad0-9b7d848ddf4c.png)

**Comment by Rafa-Gayoso** [comment]
> ponele un `console.table(gifts)` antes del return y vas a poder ver el resultado de tu objeto y de los otros test en la consola de herramientas de desarrollo.
> 
> ![image](https://user-images.githubusercontent.com/933393/144464470-ccb72c85-1cf8-4a45-91d9-91586ac42039.png)
> 
> Si queres ver la lista de entrada el pones un `consol.log` a letter.

Gracias. Probaré la sugerencia para ver los valores. Gracias por la ayuda!

**Comment by Rafa-Gayoso** [comment]
> @Rafagayoso1997 esta perfecta tu expresion regular, pero ten en cuenta que el string puede contener espacios en el principio por lo cual al hacer un replace se añade un # al principio de la cadena, luego el split toma el primer elemento como vacio, pero estas muy cerca te falta una comprobacion, un saludo!
> 
> ![image](https://user-images.githubusercontent.com/50382234/144476007-4eaa116a-e7cd-46bb-aad0-9b7d848ddf4c.png)

No pensé en esa posibilidad! Arreglaré la solución para tenerla en cuenta. Muchas gracias por la observación. Soy relativamente nuevo en JS. Muchísimas gracias!

**Comment by Rafa-Gayoso** [comment]
Ya está. Solo debía quitar los espacios en blanco al inicio de los strings. Gracias a todos.
![code3](https://user-images.githubusercontent.com/52751451/144477759-e0d2d558-172d-4a88-8509-f147bb9e3ae5.png)
