### ISSUE TITLE
Error reto #12 - ¿Cuánto cuesta el árbol?  con python

### ISSUE THREAD

**Issue by Pruiz05** [midudev/adventjs-issues#331]
## Descripción

* En los test se espera que se retorne `undefined` pero en python no existe, por lo que intento retornar `None` y me da error.

## 🧪  Test

![image](https://github.com/user-attachments/assets/7e141d6f-7670-4eff-95d3-4547e302d632)

![image](https://github.com/user-attachments/assets/88ee9ded-67f1-45ce-bce9-98cf90b701a9)

**Comment by jdelarubia** [comment]
Hola @Pruiz05 , Sólo puedo decirte que a mi en este me funcionó retornando `None`. Sin embargo, en un reto anterior, tuve que escribir `undefined` (en AdventJS) tal cual para pasarlo.

**Comment by Pruiz05** [comment]
Hola @jdelarubia y gracias 😄 , intenté  con

```py
 if (!total) return None
```

y funcionó.
