### ISSUE TITLE
Reto 7 - Aclaraciones sobre el reto

### ISSUE THREAD

**Issue by devRobots** [midudev/adventjs-issues#337]
Hola, me gustaria tener mas claridad sobre los posibles inputs del reto 7.

Según el enunciado las instrucciones de input son las siguientes:
* Recibirás un string que contiene letras y paréntesis.
* Cada vez que encuentres un par de paréntesis, debes voltear el contenido dentro de ellos.
* Si hay paréntesis anidados, resuelve primero los más internos.
* Devuelve el string resultante con los paréntesis eliminados, pero con el contenido volteado correctamente.

Esto me plantea las siguientes dudas:
1. ¿Pueden haber paréntesis mal formados? Es decir, pueden existir paréntesis sin abrir o sin cerrar en la cadena. ej: `ab)cd`
2. ¿Los paréntesis vienen en un único grupo? Es decir, si pueden haber múltiples grupos de paréntesis, ej: `ab(cd)f(gh)i`

Estas dudas me surgen dado que actualmente mi solución al reto no es capaz de superar 2 test secretos y dado que no conozco el contenido de esos test me gustaria entender la razón de fallo. Comparto mi codigo para que puedan entender cómo funciona:

```ts
function fixPackages(packages: string): string {
  const pattern = /(\w*)\(([\w\(\)]*)\)(\w*)/;
  const finds = packages.match(pattern);
  if (!finds) return packages;

  let subpackages = fixPackages(finds[2]);
  subpackages = subpackages.split("").reverse().join("");

  return finds[1] + subpackages + finds[3];
}
```

Usando recursividad y expresiones regulares obtiene el contenido de los paréntesis y lo invierte tal como pide el enunciado.

**Comment by jlmasson** [comment]
Hey @devRobots respondiendo a tu pregunta, lo hice asumiendo que el string ya viene bien formado, por lo que el enfoque está en solucionar el problema planteado.

Aquí te adjunto mi solución, lo hice con pilas:

```js
function fixPackages(packages) {
  const stack = [];

  for (let pack of packages) {
    if (pack === ")") {
      const reversed = [];
      let popPackage = stack.pop();
      while (popPackage !== "(") {
        reversed.push(popPackage);
        popPackage = stack.pop();
      }
      stack.push(...reversed);
    } else {
      stack.push(pack);
    }
  }

  return stack.join("");
}
```
