### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by franvalverde** [midudev/adventjs-issues#34]
Antes de nada, enhorabuena por darnos píldoras de conocimiento día a día.
Leí que que fuésemos reportando errores, quizás ya te lo han reportado pero tienes errores en el responsive.
Actualmente con el reto 2, se queda en xs6 toda la descripción y en la parte derecha solo un fragmento de código. La parte de la descripción es bastante complicado seguir al ser tan estrecho. La prueba ha sido en un iPhone XS. Saludos!

**Comment by midudev** [comment]
La cierro que ya tenemos una issue sobre el responsive :)
