### ISSUE TITLE
Alert

### ISSUE THREAD

**Issue by JersonGil** [midudev/adventjs-issues#35]
poder cerrar el alert al darle click

![image](https://user-images.githubusercontent.com/38517364/144496477-672da7f0-3c51-490f-8451-5b6873e349db.png)

**Comment by joseluisnoguera** [comment]
Otras posibles opciones:
- Mostrar en otro lugar
- Cambiar la opacidad

**Comment by midudev** [comment]
Ahora la notificación aparece justo debajo del editor.
