### ISSUE TITLE
Un Screen Code para poder exportar el codigo

### ISSUE THREAD

**Issue by phreakphreak** [midudev/adventjs-issues#36]

**Comment by midudev** [comment]
¿Conoces algún servicio que lo haga con una API o algo?

**Comment by Llambi** [comment]
Buenas @midudev me he encontrado estas: 
- [Code2img](https://github.com/cyberpirate92/code2img) 
- [Carbon-API](https://github.com/cyberboysumanjay/Carbon-API)

![love Midu](https://carbonnowsh.herokuapp.com/?code=We+❤️+Midu&theme=darcula&backgroundColor=rgba(255,255,255,100))

A ver si te ayudan un poco, que no todo va a ser gente con errores en los test o TypeScript. :smile:

**Comment by phreakphreak** [comment]
Encontre esta otra API que me parece que esta igual de buena [carbonara ](https://github.com/petersolopov/carbonara)
![Capture](https://user-images.githubusercontent.com/91038818/144606302-672115da-334e-498f-8f8b-3a7778994822.PNG)

**Comment by phreakphreak** [comment]
Tambien encontre esta utilidad un CLI [carbon-now-cli](https://github.com/mixn/carbon-now-cli)  de [carbon.now](https://carbon.now.sh/)

**Comment by meolivares06** [comment]
Hay libs javascript q directamente toman una captura de un HTML dado, quizas seria mas directo que usar una API.
