### ISSUE TITLE
Agregar un botón para ejecutar el código en vez de hacerlo al escribir

### ISSUE THREAD

**Issue by JGMateran** [midudev/adventjs-issues#37]
Tengo entendido de que el código se evalúa en el servidor por lo cual creo que seria mejor a nivel de gastos hacerlo de esa manera.

No parece incomodo para el usuario y además eliminas el problema de que aparezca tantas veces el tooltip cada vez (lo digo porque veo que a muchos le molesta eso)

**Comment by juanpgarciac** [comment]
Suscribo, botón de ejecución

**Comment by midudev** [comment]
Lo vamos a dejar así, ya que prefiero que el usuario no tenga que pulsar ningún botón a la hora de ejecutar los tests y sólo sea para enviar el código.

Lo que he hecho es mover los tests debajo del editor.

PD: Los tests se ejecutan en el navegador. ;)
