### ISSUE TITLE
Petición innecesaria o posiblemente erronea (https://adventjs.dev/undefined)

### ISSUE THREAD

**Issue by EverStarck** [midudev/adventjs-issues#38]
### Pero igual por si las dudas hice el issue
</br>

*Pasos de reproducción*

1. Ir a https://adventjs.dev/
2. Hacer click en retos
3. Revisar las peticiones en las dev tools

</br>

*Estado de la petición*

GET | https://adventjs.dev/undefined
Estado | 404 Not Found

**Comment by midudev** [comment]
Arreglado!
