### ISSUE TITLE
Notificaciones sobre el editor del codigo

### ISSUE THREAD

**Issue by oscarDev1190** [midudev/adventjs-issues#39]
Hola, primero que nada gracias por esta estupenda iniciativa, es muy buen aporte, felicidades.

Queria sugerir que la notificacion de ejecucion de los test deberia aparecer debajo del editor de codigo o otra area mas indicada, ya que actualmente aparece sobre el editor de texto al mismo tiempo que se esta tipeando la solucion del reto. Si bien la notificacion desaperece a los pocos segundos puede resultar algo molesto este comportamiento.

Otra posible solucion es que los test no se ejecuten automaticamente, si no que sea el usuario que los ejecutes haciendo click sobre un boton y agregarle a este boton un atajo de teclado.

saludos!

**Comment by midudev** [comment]
Ahora los tests aparecen debajo del editor.
