### ISSUE TITLE
Mejora en el diseño responsivo

### ISSUE THREAD

**Issue by xMichaelRodriguez** [midudev/adventjs-issues#40]
![Screenshot_2021-12-02-20-02-48-615_com instagram android](https://user-images.githubusercontent.com/60236402/144532294-bbefc06b-38ab-4da6-b87d-30441e8bffcf.jpg)

**Comment by itsjuancho** [comment]
Error relacionado con las Issues anteriormente abiertas: #8 y #13.

**Comment by midudev** [comment]
Duplicada!
