### ISSUE TITLE
Edge no pasa pruebas que en chrome si

### ISSUE THREAD

**Issue by QvixoteRoux** [midudev/adventjs-issues#41]
Estaba revisando un código de un colega para ver que estaba fallando en el mio, el del colega lo puse en edge y no me pasaron las pruebas, pero exactamente el mismo código (ctrl+c, ctrl+v) si me pasa en chrome, revise en firefox y tambien pasa

Usualmente uso firefox pero estare usando chrome como principal

**Comment by midudev** [comment]
¡Hola! Pásame el código y cuéntame la versión de Edge para echarle un vistazo.

**Comment by QvixoteRoux** [comment]
el codigo es este

export default function listGifts(letter) {
var lista = {};
var arrLista = letter.trim().split(" ").filter(e => !e.startsWith('_')).map(function(e){return e.trim()})
arrLista.forEach(
function(e){
lista[e] = (lista[e] || 0) +1;
}
)
console.log(lista);
return lista;

}


el edge es:Version 96.0.1054.43 (Official build) (64-bit)


estaba leyendo que resolviste un problema de que no pasaban los test si no habias hecho login, acabo de revisar y ahora si pasaron, posiblemente era ese problema ya que cuando lo revise, no habia hecho login en edge

**Comment by midudev** [comment]
Vale, gracias!
