### ISSUE TITLE
Reto 2

### ISSUE THREAD

**Issue by leonard518** [midudev/adventjs-issues#42]
Estoy generando la siguiente solucion:
`function listGifts(letter) {
    
    return letter.replace(/\s\s+/g, ' ' )
        .split(/\s/g)
        .filter( item => !item.includes('_'))
        .reduce((a, d) => ( a[d] ? a[d] += 1 : a[d] = 1, a ),{} )
}`
Y no me reconose la solucion, estoy remplazando los posibles espacios repetidos por uno simple para hacer el splir, es decir estoy considentando los espacios dobles

**Comment by Llambi** [comment]
@leonard518 prueba a ejecuta esto y mira la consola del navegador; ese replace no está haciendo lo que tu quieres 😀:

```js
export default function listGifts(letter) {
    const a = letter.replace(/\s\s*/g, ' ')
        .split(/\s/g)
    console.log({ a })
    return a
}
const regalos = listGifts('   bici coche balón _playstation bici coche    peluche   ')
```
![Captura de pantalla de 2021-12-03 13-59-31](https://user-images.githubusercontent.com/15263323/144606556-b5efc9bc-37b9-4818-8986-4df0d42e8b3e.png)

**Comment by GuillermoParedes** [comment]
Hola @leonard518 
Agrégale un trim a la cadena, para que tb elimine los espacios que pueden haber al inicio o final de cadena.

**Comment by leonard518** [comment]
@GuillermoParedes  @Llambi  gracias faltaba el trim, se me paso

**Comment by midudev** [comment]
Para dudas sobre código, mejor usar el Discord:
https://discord.com/channels/741237973663612969/915910832259477534
