### ISSUE TITLE
Comprobar el test y el resultado

### ISSUE THREAD

**Issue by Dave-JunDev** [midudev/adventjs-issues#44]
Al revisar, el ejercicio 1 y solucionarlo, y añadir mi código no permite la comprobación y genera errores, al igual con el ejercicio 2, además al comprobar su funcionamiento están realizando de manera correcta el ejercicio

**Comment by GuillermoParedes** [comment]
Si pasar el código de los ejercicios, para ver si hay algún caso que falle

**Comment by Dave-JunDev** [comment]
const ovejas = [
    { name: 'Noa', color: 'azul' },
    { name: 'Euge', color: 'rojo' },
    { name: 'Navidad', color: 'rojo' },
    { name: 'Ki Na Ma', color: 'rojo'}
    ]

export default function contarOvejas(ovejas) {
  const contarOvejas = [{}];

      ovejas.forEach(oveja => {

        let val = oveja.name.indexOf('n'&&'a') || oveja.name.indexOf('N'&&'A')
        let color = oveja.color === "rojo"

          if (val >-1 && color === true)
          {
                contarOvejas.push({name: oveja.name, color: oveja.color})
          }
      });
      contarOvejas.splice(0,1)

    return contarOvejas
}

  const ovejasFiltradas = contarOvejas(ovejas)

  console.log(ovejasFiltradas)

**Comment by GuillermoParedes** [comment]
En el enunciado pide que el nombre tenga las letras **n Y a,**  con tu enunciado estas contando ovejas de mas.
Prueba con este test, el ultimo no debería de mostrarte, porque no tiene las letras **n y a**
```javascript
const ovejas = [
{ name: 'Noa', color: 'azul' },
{ name: 'Euge', color: 'rojo' },
{ name: 'Navidad', color: 'rojo' },
{ name: 'Ki Na Ma', color: 'rojo'},
{ name: 'Ki a A Ma', color: 'rojo'},
]

```

**Comment by Dave-JunDev** [comment]
Listo, muchas gracias verifique y ahora funciona correctamente

**Comment by davorpa** [comment]
> > let val = oveja.name.indexOf('n'&&'a') || oveja.name.indexOf('N'&&'A')
> 
> _**Original posted by @Dave-JunDev at https://github.com/midudev/adventjs-issues/issues/44#issuecomment-985664049**_

Revisen la documentación de [`String.indexOf`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf)

se sorprenderian mucho de lo que se está realmente haciendo ahí.

```js
"n"&&"a"                   //always "true"
oveja.name.indexOf(true)   // always -1
```

**Comment by Dave-JunDev** [comment]
Al revisar me di cuenta de ello y era mas sencillo cambiar la validación termino siendo así
const ovejas = [
  { name: 'Noa', color: 'azul' },
  { name: 'Euge', color: 'rojo' },
  { name: 'Navidad', color: 'rojo' },
  { name: 'Ki Na Ma', color: 'rojo'},
  { name: 'Ki a A Ma', color: 'rojo'},
  ]

   function contarOvejas(ovejas) {

    const contarOvejas = [{}];

      ovejas.forEach(oveja => {

        let val = oveja.name.indexOf('N'||'n')
        let val2 = oveja.name.indexOf('A'&&'a')
        let color = oveja.color === "rojo"

          if ((val >-1 && val2 >-1) && color === true)
          {
                contarOvejas.push({name: oveja.name, color: oveja.color})
          }
      });
      contarOvejas.splice(0,1)

    return contarOvejas;
  }

  const ovejasFiltradas = contarOvejas(ovejas)

  console.log(ovejasFiltradas)
