### ISSUE TITLE
Añadir un test al día 3

### ISSUE THREAD

**Issue by carlosala** [midudev/adventjs-issues#45]
Buenas midu,

Creo que deberías añadir un test al día 3, que sería poner un parentesis puesto al revés, por ejemplo `)bici( casa play` para que de `false`. No hay ningún test del estilo, y si escribo una función que de `true` en este ejemplo, los tests pasan igual.
Buena iniciativa, y cada vez es mejor la web, buen trabajo!

**Comment by davorpa** [comment]
Efectivamente! `)` debiera estar siempre tras `(`.

Otros test a valorar muy comunes en un parser AST...
- ✅ `(coche (barbie) balón) casa` todos los paréntesis anidados tienen su pareja
- ❌ `(puzzle carbón) cuerda) tablet` ó `(chuches (tarjeta libro) ropa` falta algún paréntesis anidado de apertura o cierre
- ❌ `(   )` ó `(  (  )   )` ó `(  (guantes)   )` solo espacios entre paréntesis

Extras:
- ✅ `tele (ropa) dvd (puzzle)` multiples paréntesis emparejados
- ✅ `airbuds(reloj)vhs` sin espacios entre palabra y paréntesis
- ✅ `(lego   build)` single/multi espaciado entre parabras dentro de paréntesis
