### ISSUE TITLE
Ejercicio 2

### ISSUE THREAD

**Issue by ArkoxHub** [midudev/adventjs-issues#46]
No me deja completar el ejercicio y en mi navegador me sale perfecto.

`
export default function listGifts(letter) {
const regalos = {}

// Elimino los espacios
letter = letter.split(/\s+/);

// Agrego los regalos al objeto
letter.forEach(element => {
    if (regalos[element]) { regalos[element] ++ }

    if (!regalos[element] && !element.includes("_")) {
        regalos[element] = 1;
    }
});
return regalos;
}
`

Me parece que no has tenido en cuenta los espacios dobles en blanco...trim trim trim!

**Comment by GuillermoParedes** [comment]
@ArkoxHub tb tienes que contemplar que pueden haber espacios al inicio y/o al final de cadena, un trim puede ayudarte

**Comment by ArkoxHub** [comment]
Listo, pero creo que lo tenía igual de bien por las pruebas que hice en local

**Comment by silverbryan** [comment]
Hola @ArkoxHub,
El problema con tu codigo es que no contemplas los espacios que pueden haber en el principio de la cadena.
Entonces al hacer el split, añade un campo vacio al array y despues se añade un atributo vacio al objeto como por ejm:

```javascript
{ 
  '': 1, 
  bici: 2, 
  coche: 2, 
  balon: 1, 
  peluche: 1 
}
````
![image](https://user-images.githubusercontent.com/50382234/144666549-1c7a6ccb-d14b-474e-a481-875b5dada5af.png)

**Comment by davorpa** [comment]
> ```js
> // Elimino los espacios
> letter = letter.split(/\s+/);
> ```

En que parte de internet se dice que `split` elimina espacios? Split parte un string a array

> ```js
> letter.forEach(element => {
>     if (regalos[element]) { regalos[element] ++ }
>     ...
> });
> ```

No es recomendable mutar objetos de un closure superior dentro de un `Array.forEach`. Puede provocar memory leaks y resultados inesperados.

Para eso existe el `Array.reduce`

```js
arr.reduce((regalos, element, index, arr) => (
    // init obj key && increment
    regalos[element] = (regalos[element] || 0) + 1,
    // return
    regalos
  ),
  // init obj
  {})
```

**Comment by ArkoxHub** [comment]
> > // Elimino los espacios
> 
> > letter = letter.split(/\s+/);
> 
> 
> 
> En que parte de internet se dice que `split` elimina espacios?

En la que el regex de dentro lo hace primo

**Comment by davorpa** [comment]
> En la que el regex de dentro lo hace primo

Nada mas lejos de la realidad primo.

**`split(/\s+/)` NO elimina espacios**. Lo que evita es procesar varios espacios seguidos a la hora de generar el array y por tanto que aparezcan cadenas vacías como elementos del mismo.

**Comment by midudev** [comment]
Para dudas sobre código, mejor usar el Discord de la comunidad:
https://discord.com/channels/741237973663612969/915910832259477534
