### ISSUE TITLE
Volver a ver el resultado

### ISSUE THREAD

**Issue by JuanjoOrt** [midudev/adventjs-issues#47]
Hola,

Una vez que mandas el resultado ya no veo manera de volver a verlo por si se lo quieres enseñar a algún amigo o algo.

Lo primero que se me ocurre es que la misma bbdd donde guardas la solución tenga una API GET para devolverlo cuando vuelves a entrar

**Comment by itsjuancho** [comment]
Hace referencia a lo mismo que se comenta en la sugerencia #29.

**Comment by equiman** [comment]
Ya esta resulto. Desde hoy guarda el codigo si logras resolverlo.

**Comment by midudev** [comment]
Ahora se guardan las soluciones. Así que cierro esto!
