### ISSUE TITLE
[BUG] All test passing with incorrect solution 

### ISSUE THREAD

**Issue by ientu** [midudev/adventjs-issues#48]
**Description**

Using this code in the second "reto" all tests was incorrectly valid:

```
export default function listGifts(letter) {
letter = letter.trim();
return {}
}
```

**Evidences**

![Animation](https://user-images.githubusercontent.com/29860103/144652990-6d2b00f6-0ddd-460f-b323-4809fa45abc0.gif)

**Comment by srubio131** [comment]
Me too! I think that when you are not logged in, the tests are always correct.
Try logging in to your github account and you'll see that the tests come out wrong.

**Comment by midudev** [comment]
Ya se ha solucionado el problema que los usuarios no logueados siempre pillaban los tests como correctos. :)
