### ISSUE TITLE
no entiendo por que no puedo mandar el segundo reto

### ISSUE THREAD

**Issue by Alejano** [midudev/adventjs-issues#49]
![image](https://user-images.githubusercontent.com/25163085/144655752-cb2a5e23-9ca5-4ee4-a642-fb7a102a56ae.png)
 no comprendo, este es mi codigo 

var new_letter = new Object();
const words = letter.split(' ');

for(var i in words){
 var nojuguete = words[i].search("_");
if(nojuguete == -1){
 if(words[i] in new_letter){
   new_letter[words[i]] = new_letter[words[i]]+1
 }else{
   new_letter[words[i]] = 1
 }
}
     
 }
 console.log(new_letter)

**Comment by GuillermoParedes** [comment]
@Alejano tb tienes que contemplar que pueden haber espacios al inicio y/o al final de cadena, un trim puede ayudarte

**Comment by maxiconstancio** [comment]
Hola Me pasa lo mismo  y estoy eliminando los espacios con la expresion regular: 

export default function listGifts(letter) {
 // ¡Tú puedes!
    let expReg = /\s+/;
    let arrCarta = letter.split(expReg);
    let repetidos = {};
    arrCarta.forEach(function(regalo){
        if (regalo.charAt(0) != '_') {
            repetidos[regalo] = (repetidos[regalo] || 0) + 1;
        };
    });
    return repetidos;
}

**Comment by itsjuancho** [comment]
> Hola Me pasa lo mismo y estoy eliminando los espacios con la expresion regular:
> 
> export default function listGifts(letter) { // ¡Tú puedes! let expReg = /\s+/; let arrCarta = letter.split(expReg); let repetidos = {}; arrCarta.forEach(function(regalo){ if (regalo.charAt(0) != '_') { repetidos[regalo] = (repetidos[regalo] || 0) + 1; }; }); return repetidos; }

@maxiconstancio prueba con el siguiente caso de test: `'                bici coche balón _playstation bici coche peluche      '`. En teoría estás haciendo el split, que es como cortar en rebanadas donde haya cada espacio; pero si te fijas en el caso de test anterior, la cadena puede tener espacios al inicio y final, y aún así, el split tomará en cuenta esos espacios y los devolverá como elementos vacíos al array que retorna. Si usas .trim() primero y luego el .split(expReg), te eliminará los espacios y ahí sí debería de pasar los tests. Espero te sirva de ayuda.

**Comment by maxiconstancio** [comment]
Perfecto, pude observar que haciendo el test con el caso que me enviaste no esta funcionando como debe, ahora queda corregir y probar nuevamente. Muchas gracias! Saludos!

**Comment by davorpa** [comment]
Quizás el problema sea que la mayoría de la gente entiende que `split(/\s+/)` elimina espacios, cuando en realidad lo que evita es procesar varios espacios seguidos a la hora de generar el array y por tanto te aparezcan cadenas vacías como elementos del mismo.

También puede usarse los ["lookup assertions"](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions) si se quiere hacer todo con expresiones regulares. Algo como:
```js
 string.split(/(?>^\s+)|(\s+)|(?!\s+$)/g)
```

**Comment by midudev** [comment]
Para dudas sobre código, mejor usar el Discord de la comunidad:
https://discord.com/channels/741237973663612969/915910832259477534
