### ISSUE TITLE
Cambiar el favicon

### ISSUE THREAD

**Issue by nikosantis** [midudev/adventjs-issues#5]
Un cambio pequeño pero significativo:
- colocar un favicon con el mismo diseño ya utilizado en el sitio 👍

Quizás a partir del "logo"(?)

<img width="118" alt="Captura de Pantalla 2021-12-01 a la(s) 14 18 49" src="https://user-images.githubusercontent.com/5368594/144282126-ca1c88f5-3eb6-4454-b331-ed32bb10c88a.png">

**Comment by equiman** [comment]
Se pueden usar algunos asociados a la navidad:

https://www.flaticon.com/free-icons/christmas-tree

**Comment by midudev** [comment]
Hecho!
