### ISSUE TITLE
Ejercicio 3

### ISSUE THREAD

**Issue by ArkoxHub** [midudev/adventjs-issues#50]
Esta función en local me va perfecto, pero al pasarlo a la consola de la web me dice bici debería ser inválido, e inválido lo es, pero no lo acepta.

`    function letterIsValid(letter) {
        if (letter.includes("(") && letter.includes(")")) {
            const openedParentesis = letter.indexOf("(");
            const closedParentesis = letter.indexOf(")");
            
            if (openedParentesis < closedParentesis) {
                const wordInsideParentesis = letter.substring(openedParentesis + 1, closedParentesis);
                if (wordInsideParentesis.length == 0 || wordInsideParentesis.includes("{") || wordInsideParentesis.includes("[")) {
                    return false;
                }
                return true;
            }
        }
        return false;
    }    `

**Comment by itsjuancho** [comment]
Utiliza el siguiente caso de test: `(()) bici`.

Dado el anterior caso, aún así seguirá escapando un paréntesis de apertura solo, y es por eso que te da el error.  Para verlo mejor, luego de la línea diez, haz un `console.log` o un `return` de `wordInsideParentesis`.

Ten en cuenta lo que decía el enunciado: `Para saber si una carta es válida ✅, debes comprobar que los paréntesis cierran correctamente y que, además, no vayan vacíos.`  👈🏻 Como el string tiene el paréntesis de apertura, pero no de cierre, por eso falla el test; porque aunque te lo tire como true, debería ser false. Espero haberme dado a entender y que te pueda servir de ayuda.

**Comment by midudev** [comment]
Para dudas sobre código, mejor usar el Discord de la comunidad:
https://discord.com/channels/741237973663612969/915910832259477534
