### ISSUE TITLE
1er día no valida una vez que me logueo

### ISSUE THREAD

**Issue by danmarz** [midudev/adventjs-issues#53]
Hola Miguel, estoy empezando con el reto y esto es lo que me pasa, 

## Aquí hay spoilers!
<details>
  <summary>Click meh!</summary>
  
  ## Cuando no estoy logueado
![Screenshot 2021-12-03 210810](https://user-images.githubusercontent.com/58673649/144667240-a93d4259-a479-47d2-a47f-ac981317b177.png)
 ## Cuando me logueo (con GitHub Oauth if it matters) me sale el error y el botón de submit queda deshabilitado.
![Screenshot 2021-12-03 210746](https://user-images.githubusercontent.com/58673649/144667134-a129d2cb-5636-4fe4-b178-08295d828c75.png)
Alguna idea sobre cuál podía ser el pb?
</details>

**Comment by davorpa** [comment]
Existe un bug con el login y el editor.

Lo correcto es estando identificado.

**Comment by midudev** [comment]
El problema es que con login tu código no es correcto. Estás mirando si tiene la letra a o n y debería ser la letra a Y la n, las dos a la vez.

**Comment by danmarz** [comment]
Gracias🙌 es verdad, funciona bien sin los `[` `]`. 
El problema es que con el input de ovejas que tenemos, el .match() con `[]` también da [el resultado esperado](https://stackblitz.com/edit/node-okgoei). 

Una propuesta para que esto no sea el caso (para dar más claridad) es añadir una oveja al array que **NO** tenga la `n` o la `a`  tipo:
`{ name: 'Nugget', color: 'rojo' }`
