### ISSUE TITLE
test no funcionan al estar logueado

### ISSUE THREAD

**Issue by EdisonAvila19** [midudev/adventjs-issues#54]
Hola Miguel, estoy tratando de enviar el reto 3, al estar login me dice que la respuesta es incorrecta, y sin login si me muestra que la respuesta es correcta.

Gracias por estos retos, los estoy disfrutando!!

**Comment by davorpa** [comment]
Existe un bug con el login y el editor de código.

Lo correcto es estando identificado

**Comment by midudev** [comment]
Ya se solucionó que sin estar logueado te pasase siempre los tests. Vuelve a revisar.
