### ISSUE TITLE
Ejercicio 3 

### ISSUE THREAD

**Issue by fredneyparra0** [midudev/adventjs-issues#58]
Este codigo funciona mas no deberia de pasar los test ya que no estamos validando el contenido dentro de los parentesis

export default function isValid(letter) {
    const validP = letter.includes('(') && letter.includes(')');
    const invalid = !letter.includes('{') && !letter.includes('[') && !letter.includes('()') 
    return validP && invalid
}

un saludo

**Comment by davorpa** [comment]
Efectivamente falta validar algunas cosas. Quizás porque se cuentan parejas

Más o menos lo comentado en #45

**Comment by midudev** [comment]
Para dudas sobre código, mejor usar el Discord de la comunidad:
https://discord.com/channels/741237973663612969/915910832259477534
