### ISSUE TITLE
Muy dificil de debuggear

### ISSUE THREAD

**Issue by TTorr3** [midudev/adventjs-issues#59]
Es muy dificil ver que esta pasando sin ver la salida que genera nuestro codigo, seria muchisimo mas facil teniendo una impresion de nuestro resultado actual. 
Muy buenos desafios igualmente!

**Comment by davorpa** [comment]
Si. estaría bien tener un panel dónde se arrojaran tanto los resultados de test como las trazas de `console.XXX` o compilación

**Comment by equiman** [comment]
Pueden usar las herramientas de desarrollo del navegador.  En el codigo adicionar `console.log` para que te imprima en consola o usar la palabra `debugger` y eso te hace un breakpoint al pasar por ahi.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger

**Comment by davorpa** [comment]
> Pueden usar las herramientas de desarrollo del navegador. En el codigo adicionar `console.log` para que te imprima en consola o usar la palabra `debugger` y eso te hace un breakpoint al pasar por ahi.

Lo sé, solo que en los dispositivos móviles no existe tal herramienta y aunque pongas `console.log` o `alert` no aparecen

**Comment by midudev** [comment]
He mejorado sensiblemente el feedback que dan los tests.
