### ISSUE TITLE
En challenge 02

### ISSUE THREAD

**Issue by zenbakiak** [midudev/adventjs-issues#61]
Corrí tests sobre mi función y a menos que estén validando otra cosa no encuentro fallo, no obstante el ejercicio se marca como incorrecto, argumentando que no se están cuidando los dobles espacios, aún cuando es el primer filtro que hago.

```js 
export default function listGifts(letter) {
  const result = {}; 
  letter
    .split(' ')
    .filter(String)
    .filter(x => !x.includes('_'))
    .map(x => { 
      result[x] = (letter.match(new RegExp(x, 'g')) || []).length 
    }); 
  return result 
}
```

![image](https://user-images.githubusercontent.com/4805047/144701443-a38f1447-9f37-4f06-8256-d403918aaeac.png)

**Comment by tasiodev** [comment]
Según lo has hecho, cuando pones una palabra que contiene las mismas letras que otra, lo cuenta cuando lo encuentra dentro de otras palabras, por ejemplo:

![image](https://user-images.githubusercontent.com/39553179/144706705-e1e774f4-f116-46b5-a674-5e2c820ca674.png)

Quizá aunque el tooltip diga lo de los espacios, el problema viene por aquí

**Comment by davorpa** [comment]
Muy ingenioso usar `String` para zafarse de las cadenas vacías en el array.

prueba tambien a pasar a:

- `split(/\s+/g)` cualquier espacio / tabulador... muti o no, 
- `filter(x => !x.startsWith('_'))` fix para `"peluche ar_bol"` que debiera ser válido

Recomendaciones:
- Los regex deben ser escapados. E.g.: `"coche (bici>.+ mono"` da error de compilación porque `(bici>.+` no es regex válida.
- Evitar mutar objetos de closures superiores. Pueden provocar resultados inesperados en entornos de concurrencia, también memory leaks. Esto es... el `map` debería ser un `reduce`:
  ```js
  arr.reduce((result, x) => (
      // register amount
      result[x] = /* your code */,
      // return
      result
    ),
    // init result object
   {});

**Comment by midudev** [comment]
Como te han comentado, el código no es correcto. :) A por el reto!
