### ISSUE TITLE
Posible error en uno de los tests del cuarto desafío

### ISSUE THREAD

**Issue by DamianCabrio** [midudev/adventjs-issues#62]
Hola, estaba haciendo el cuarto desafió de crear el árbol de navidad, pero me está tirando un error de que "¡No has hecho el árbol de dos niveles correctamente!", pero fijándome en la consola, y teniendo en cuenta los ejemplos, parece que el árbol se está creando bien, pero puede que yo no me esté dando cuenta de algo.

Así escribe el árbol de 2. Tiene 1 sola estrella arriba, como los ejemplos, la segunda línea agrega 2 estrellas más que la línea anterior, tiene 2 líneas de base, y todo tiene el mismo ancho

![image](https://user-images.githubusercontent.com/45396062/144712497-98a71957-3b65-497d-8366-b150eab072d9.png)

Este es mi código
![code](https://user-images.githubusercontent.com/45396062/144712593-487ed6cc-e9ea-431f-9329-12f9429d2ec8.png)

No sé si a alguien más le pasa o yo seré el único.

**Comment by ProdByGR** [comment]
Prueba quitando el salto de linea `\n` en la ultima linea

**Comment by felipeteko** [comment]
Intenta poniendo un trim al momento del return

`return tree.trim();`

Recuerda que los test automatizados hacen comparación del string completo.

**Comment by DamianCabrio** [comment]
> Intenta poniendo un trim al momento del return
> 
> `return tree.trim();`
> 
> Recuerda que los test automatizados hacen comparación del string completo.

Era eso, ¡Muchas gracias!
