### ISSUE TITLE
listGifts

### ISSUE THREAD

**Issue by aldanadc** [midudev/adventjs-issues#63]
Hola!

Sé que menciona que para este ejercicio los tests pueden ser más exhaustivos pero mi solución funciona e igualmente me da error y no me deja enviarlo :(

**Comment by equiman** [comment]
Si dejas el código por acá alguien podría ayudarte.

**Comment by aldanadc** [comment]
`export` default function listGifts(letter) {
 // ¡Tú puedes!
  const result = {};

  letter = letter.replace(/\s+/g,' ').trim();

  const splitString = letter.split(" ");

  splitString.forEach((word, index) => {

    if (word[0] === "_") {
      splitString.splice(index, 1)
    }
    
  });

  splitString.forEach(word => {
    if (!result[word]) {
      result[word] = 1;
    }else {
      result[word] +=1;
    }
  })

  return result
 
}

**Comment by aldanadc** [comment]
Probé con muchos ejemplos y para mí funciona, pero en el editor del challenge me dice que no tengo en cuenta los espacios dobles. Gracias por la ayuda!

**Comment by DamianCabrio** [comment]
Si pones un console.log en la función y te metes a la consola del inspector podés ver cuál es el test que falla.
![imagen](https://user-images.githubusercontent.com/45396062/144722775-8c831664-c32b-485b-a9bd-a286ece3acc1.png)
Parece que el filtro de los _ está fallando cuando la palabra completa es solo un _
Cambiando esa parte del código me anduvo tu respuesta. Podés probar con un filter o algo parecido.

**Comment by aldanadc** [comment]
Gracias Damián! En realidad al usar word[0] debería funcionar tanto si la palabra entera es un "_" o como si es el primer caracter. No sé bien qué habrás cambiado vos para que te funcionara pero yo lo que encontré que estaba funcionando mal era el splice, lo hice de otra forma y ahora sí pasan los tests.

Gracias por la ayuda!
