### ISSUE TITLE
Reto 4 - No funciona

### ISSUE THREAD

**Issue by gribera** [midudev/adventjs-issues#64]
Hola, parece que el reto 4 no está funcionando. Lo probé localmente y me funciona, pero cuando intento enviar el código me dice "¡No has hecho el árbol de 2 niveles!", cosa que es imposible porque si lo pruebo localmente funciona bien

**Comment by equiman** [comment]
Seguro es lo mismo que nos paso a varios. Ya esta comentado aca https://github.com/midudev/adventjs-issues/issues/62

**Comment by gribera** [comment]
gracias!, era eso.
