### ISSUE TITLE
Propuesta para el botón de modo oscuro

### ISSUE THREAD

**Issue by JGMateran** [midudev/adventjs-issues#66]
TailwindCSS en su documentación ([https://tailwindcss.com/docs/dark-mode](https://tailwindcss.com/docs/dark-mode)) tiene un ejemplo de como utilizar el modo oscuro

```
if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
  document.documentElement.classList.add('dark')
} else {
  document.documentElement.classList.remove('dark')
}
```

Estaría muy buen convertir esto es un hook de React y utilizarlo en un botón.

**Comment by davorpa** [comment]
Same as #65

**Comment by midudev** [comment]
Duplicated.
