### ISSUE TITLE
¿es posible usar expresiones regulares?

### ISSUE THREAD

**Issue by Saeron** [midudev/adventjs-issues#67]
```
regex = /([^\(\)]*\([^\{\}\[\]]+\)[^\(\)]*)+/g
    cadenas = letter.match(regex)
    if(cadenas != null && cadenas.length == 1 && cadenas[0].length == letter.length){
        return true
    }
    return false
```
Me dice que el código no parece correcto, no se si es que no pasa los test o que no reconoce las expresiones regulares.
PD: Es del ejercicio 3, pero no creo que eso vaya ligado con lo que pregunto.

**Comment by DamianCabrio** [comment]
Si funcional el regex, creo que el error es que te falto poner const o let en frente de las variables. Yo copié tu código e hice eso, y el código corrió, pero igual hubo un fallo en algún test, dice que (()) debe fallar.

**Comment by EdgarAyllon** [comment]
Parece ser que fallan.

**Comment by davorpa** [comment]
> creo que el error es que te falto poner const o let en frente de las variables

No tiene que ver, aunque si es buena práctica para evitar memory leaks y variables globales

`/([^\(\)]*\([^\{\}\[\]]+\)[^\(\)]*` no tiene en cuenta que los pares vayan en orden y haya el mismo número de aperturas que de cierres. `a) b (c` no debería se válido

**Comment by DamianCabrio** [comment]
> > creo que el error es que te falto poner const o let en frente de las variables
> 
> No tiene que ver, aunque si es buena práctica para evitar memory leaks y variables globales
> 
> `/([^\(\)]*\([^\{\}\[\]]+\)[^\(\)]*` no tiene en cuenta que los pares vayan en orden y haya el mismo número de aperturas que de cierres. `a) b (c` no debería se válido

Si no lo pones te tira en la consola error de que regex y cadenas no está definidos y no corren los tests

**Comment by davorpa** [comment]
👍 

> Si no lo pones te tira en la consola error de que regex y cadenas no está definidos y no corren los tests

seguramente porque la plantilla dónde se incrusta el código usa `"use strict";` al principio del scope

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

**Comment by Saeron** [comment]
DamianCabrio tiene razon, el problema esta en que necesitas poner const o let en las variables.
