### ISSUE TITLE
Tests pasan en Brave y no en Firefox

### ISSUE THREAD

**Issue by DamianCabrio** [midudev/adventjs-issues#68]
Hola, estaba haciendo el desafío 4 y no me estaba funcionando (lo estaba haciendo en Firefox), cambia al navegador Brave para probar y en este si pasaron, y era exactamente el mismo código.
Hasta ahora todos los otros desafíos habían pasado bien en Firefox, este fue el único que tuvo este problema.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/45396062/144724160-22b809ff-a611-4f8d-974f-911fea679e8c.gif)

Este es el código:
``` 
function createTreeLine(
  maxSpaces,
  maxMiddleCharacter,
  middleCharacter = "*",
  spaceCharacter = "_"
) {
  const spaces = spaceCharacter.repeat(maxSpaces);
  const middle = middleCharacter.repeat(maxMiddleCharacter);
  return `${spaces}${middle}${spaces}\n`;
}

export default function createXmasTree(height) {
  var tree = "";
  for (var i = 0; i < height + 2; i++) {
    if (i < height) {
      tree += createTreeLine(height - i - 1, i * 2 + 1);
    } else {
      tree += createTreeLine(height - 1, 1, "#");
    }
  }
  return tree.trim();
}  
```

¡Muchas gracias!

**Comment by midudev** [comment]
Por desgracia en Firefox no podemos soportar funciones dentro de la función principal. Seguramente por eso no te funciona. Para asegurarte que todo va bien, crea siempre sólo una función.
