### ISSUE TITLE
Ejercicio 1 no pasa un test que debería estar correcto

### ISSUE THREAD

**Issue by Losina24** [midudev/adventjs-issues#69]
Este es mi código para el ejercicio 1:
```js
export default function contarOvejas(ovejas) {
  return ovejas.filter( oveja => {
    if(oveja.color == "rojo" && /a|n|A|N/g.test(oveja.name) ) return true
    return false
  })
}
```

Al ejecutar un console.log me devuelve el resultado correctamente pero el ejercicio sigue indicándome que está mal, ¿es algún error con mi código o no se admiten expresiones regulares?

**Comment by DamianCabrio** [comment]
Creo que el error es que lo que debes devolver es una lista con las ovejas que cumplan con los requisitos dados, pero ahí estás devolviendo true o false.

> Por ejemplo, si tenemos las ovejas:
const ovejas = [
  { name: 'Noa', color: 'azul' },
  { name: 'Euge', color: 'rojo' },
  { name: 'Navidad', color: 'rojo' },
  { name: 'Ki Na Ma', color: 'rojo'}
]<br>
Al ejecutar el método debería devolver lo siguiente:
const ovejasFiltradas = contarOvejas(ovejas)
console.log(ovejasFiltradas)
// [{ name: 'Navidad', color: 'rojo' },
//  { name: 'Ki Na Ma', color: 'rojo' }]

**Comment by Losina24** [comment]
estoy devolviendo la lista de ovejas que cumplen las condiciones del filter(). El true y false son las respuestas del callback del filter

**Comment by DamianCabrio** [comment]
> estoy devolviendo la lista de ovejas que cumplen las condiciones del filter(). El true y false son las respuestas del callback del filter

Ah Disculpa, vi mal. Creo que el error es que el desafío dice que tiene que devolver las ovejas que tengan en su nombre n Y a, pero estás devolviendo algunas con solo una de esas letras
![imagen](https://user-images.githubusercontent.com/45396062/144725702-1ba98154-536d-4724-8eb8-cc4ff14c2627.png)

**Comment by Losina24** [comment]
Ahhh es cierto, no me fije, ese era el problema jajajaja, muchas gracias
