### ISSUE TITLE
Icono erroneo en el toast cuando hay un error en el código

### ISSUE THREAD

**Issue by nistadev** [midudev/adventjs-issues#7]
Al tener el codigo con errores (sin pasar tests) aparece un icono de ✅ envez de ❌. Tampoco hay feedback de color.

**Screenshot**
![image](https://user-images.githubusercontent.com/22194171/144287403-e5fa3312-90ac-405e-8511-743ed89cc486.png)

**Comment by midudev** [comment]
Arreglado!
