### ISSUE TITLE
[BUG] Test OK con solución incorrecta

### ISSUE THREAD

**Issue by aortega46** [midudev/adventjs-issues#70]
### 01 Contando ovejas para dormir
**Descripción**
Los tests pasan la prueba cuando realmente devuelve:
```
{ name: "Euge", color: "rojo" }
{ name: "Ki Na Ma", color: "rojo" }
```

![bug](https://user-images.githubusercontent.com/29067122/144727099-bb89485f-c629-4077-8b33-c5a0b91df355.gif)

**Código**
```
export default function contarOvejas(ovejas) {
    return ovejas.filter(e => e.color === 'rojo' && e.name.search(/[na]/i))
}
```

---

Search si no encuentra devuelve -1 -> la condición no se cumple

Match si no encuentra devuelve null

**Solución alternativa** con match que SI funciona y devuelve las ovejas correctas:
```
return ovejas.filter(e => e.color === 'rojo' && e.name.match(/[na]/i))
```

Con search no consigo entender porqué devuelve Euge si no tiene ni 'n' ni 'a' en el nombre  y porqué no devuelve Navidad. Agradecería si alguien sabe explicarme porqué.

 ---

¡Gracias midu por currártelo tanto!

**Comment by TeoDiaz** [comment]
Hola. Voy a intentar explicarme, estos son los outputs de las dos funciones: 

```
> str = "Euge"
'Euge'
> str.search(/[na]/i)
-1
> str.match(/[na]/i)
null
```

Como puedes ver, search devuelve `-1` y match devuelve `null`. Al hacer el filter, si dices que `-1` es valido y no lo filtra. 

Si quieres usar search,  puedes ponerle un `!`delante

```
> arr = ["Euge", "Navidad"]
[ 'Euge', 'Navidad' ]
> arr.filter(x => x.search(/[na]/i))
[ 'Euge' ]
> arr.filter(x => !x.search(/[na]/i))
[ 'Navidad' ]
```

Espero haberte aclarado un poco 😉

**Comment by aortega46** [comment]
> Finalmente solo me queda decir que pese a haber resuelto mi duda, los tests igualmente siguen dando por válida la solución con `search` pese a ser **incorrecta**. Perdón por el tocho 😅

Buenas. Quizá no he acabado de entender, pero pasa algo raro. Voy a poner los diferentes casos e intentar comprender lo que está pasando.

Dado la siguiente lista/array de nombres
`const arr = ['Noa', 'Euge', 'Navidad', 'Ki Na Ma']`

## Search
### Situación
```
const search1 = arr.filter(e => e.search(/[na]/i))
// search1: [ 'Euge', 'Ki Na Ma' ]

const search2 = arr.filter(e => !e.search(/[na]/i))
// search2: [ 'Noa', 'Navidad' ]
```
### Análisis
Podemos observar como en `search1` ha filtrado un caso que tiene `n` o `a`.  Analicemos el comportamiento de manera aislada:

```
str1 = "Euge"
str1.search(/[na]/i)
// -1

str2 = "Ki Na Ma"
str2.search(/[na]/i)
// 3
```
Como vemos `Euge` devuelve  `-1` y `Ki Na Ma` devuelve `3`. ¿Porqué motivo se filtra o se filtran cuando la condición no se está cumpliendo? 

> ******* Analizando la situación en las siguientes líneas me doy cuenta de lo que está pasando, pero voy a dejarlo aquí explicado igualmente  por si puede ser de ayuda *******

Haciendo lo mismo con `Navidad` y `Noa` podemos ver que el resultado es `0` porque la `n` o `a` está en primera posición.
```
str1 = "Navidad"
str1.search(/[na]/i)
// 0

str2 = "Noa"
str2.search(/[na]/i)
// 0
```
**Conclusión**

Entonces `search` está actuando ciertamente como un `boolean` aceptando así solo 2 posibles _inputs_ para filtrar, que serian `-1` y `0`, visto de otra manera `false` o `true`.

---

## Match

Con `match` esto no pasa, curiosamente la negación funciona justamente al revés y por eso también me confundía el `search`.

```
const match1 = arr.filter(e => e.match(/[na]/i))
// match1: [ 'Noa', 'Navidad', 'Ki Na Ma' ] 

const match2 = arr.filter(e => !e.match(/[na]/i))
// match2: [ 'Euge' ] 
```

### Analisis

```
str1 = 'Noa'
str1.match(/[na]/i)
// str1: ["N"]

str2 = 'Euge'
str2.match(/[na]/i)
// null

str3 = 'Navidad'
str3.match(/[na]/i)
// str3: ["N"]

str4 = 'Ki Na Ma'
str4.match(/[na]/i)
// str4: ["N"]
```

**Conclusión**
Con `match` si nos devuelve un valor es `true` y si nos devuelve `null` es `false`.

---

Gracias por la ayuda 😊

**Comment by midudev** [comment]
Arreglado el test (era un poco pirata :P).
