### ISSUE TITLE
Reto 4 no consigo hacerlo pasar

### ISSUE THREAD

**Issue by gabrielmenor** [midudev/adventjs-issues#71]
Estoy creando dos bucles para pintar el arbol con la altura que recibe por parámetro como dice en las indicaciones.
`export default function createXmasTree(height) {
  let result = ''
  for(let i=0; i<(height+2); i++) {
    for(let z=0; z<((height*2)-1); z++) {
      if(i >= height) {
        if(z === height-1) {
          result += '#'
        } 
        else {
          result += '_'
        }
      }
      else if(z === height-1) {
          result += '*'
      } 
      else if(z < ((height)-i)-1) {
        result += '_'
      } 
      else if(z >= (height)+i) {
        result += '_'
      } 
      else {
        result += '*'
      }
    }
    result += '\n'
  }
  console.log(result)
  return result
}`
![image](https://user-images.githubusercontent.com/7412810/144727841-e9c1c08e-f537-4d15-8483-a76cc90548e0.png)

Porfa, alguien puede ayudarme?

Mil gracias!

**Comment by TeoDiaz** [comment]
Hola, he probado tu código y el error esta en la ultima linea. 

`result += '\n'` esto añade un `\n` al final del todo y tu árbol tiene un salto de linea de mas. 

```
_*_
***
_#_
_#_
       <-- este salto de linea no debería estar
```

Dale una vuelta, casi lo tienes 😉

**Comment by bags3031** [comment]
No he logrado pasar este reto, tengo el error No has hecho el árbol de dos niveles correctamente!, pero veo que lo esta creando bien.

![reto 4](https://user-images.githubusercontent.com/3276146/144735302-1fd8a309-40b6-48f8-9cfa-990c37aa98af.png)

export default function createXmasTree(height) {
        let altura = height;
        let limite = altura * 2 - 1;
        let impar = 1;
        let cadena ='';
        
        for(let i=1;i<=altura;i++){
          if(i!=1){
            impar = impar + 2;
          }                    
          for(let j=1;j<=limite;j++){
            let k =altura-i;
            
            if(j<= k){
              cadena = cadena + "_";
            }else{
              if(j==limite){
                if(k!=0){
                  cadena = cadena + "_\n";
                }else{
                  cadena = cadena + "*\n";
                }                
              }else{
                if(j>k+impar){
                  cadena = cadena + "_";
                }else{
                  cadena = cadena + "*";
                }                
              }
            }            
          }          
        }

        for(let l=1;l<=2;l++){
          for(let m=1;m<=limite;m++){
            if(altura==1){
              cadena = cadena + "#\n";
            }else{
              if(m==limite){
                cadena = cadena + "_\n";
              }else{
                if(m!=altura){
                  cadena = cadena + "_";
                }else{
                  cadena = cadena + "#";
                }
              }
            }           
          }
        }
        console.log(cadena);
  return cadena;
}

**Comment by bags3031** [comment]
Esta solución te servirá #62.

**Comment by gabrielmenor** [comment]
Gracias por la ayuda Teo, pero no era eso, tenía correctamente los saltos
de linea.....sabes que era?
Los espacios... he hecho un trim() al resultado y entonces si pasan los
tests....mira que lo pensé....
