### ISSUE TITLE
Manual test run

### ISSUE THREAD

**Issue by Cjescalona1** [midudev/adventjs-issues#72]
considero la integracion de un boton para correr los test para evitar errores en el runtime ,  en el transcurso de la escritura de un ciclo while se creo un bucle infinito mientras se escribia (bevido a que corrio el test mientras se escribia), o tambien veo la posibilidad de desactivar los test automaticos y luego activarlos nuevamente.

**Comment by midudev** [comment]
Repe!

**Comment by Cjescalona1** [comment]
Vale gracias por revisar...
