### ISSUE TITLE
Desafios Navidad

### ISSUE THREAD

**Issue by GaspiCastello** [midudev/adventjs-issues#73]
Midu, recién termino el desafío del grinch #3. Me atrasé un día pero valió la pena. 
Mi sugerencia es agregar como regla que no haya paréntesis dentro de los paréntesis ya que el testeo arroja el siguiente error:
" ( ( ) ) bici " debe ser invalido
Seguramente mi código no es bueno, recién inicio mi carrera en esto. Te agradezco comentarios para mejorarlo!!

**Comment by xMichaelRodriguez** [comment]
```
const valid = /(\([^\s\)\{\}\[\]]*\))/g;
    if (valid.test(letter)) {
        return true
    }
    return false
```

yo utilice esa expresion regular para ese ejercicio y me fue bien 👌

**Comment by midudev** [comment]
En el ejercicio se dice que no puede haber unos paréntesis vacíos sin nada dentro. Si te fijas, el `(())` hace que tengas unos paréntesis vacíos. :)
