### ISSUE TITLE
Ejercicio uno no pasa test

### ISSUE THREAD

**Issue by xMichaelRodriguez** [midudev/adventjs-issues#74]
el test me dice que estoy contando ovejas de mas pero e probado y lit me devuelve las ovejas como en el ejemplo en la plataforma :(
```js
function contarOvejas(ovejas) {
    ovejas = ovejas.filter(o => {
        const color = o.color.toLowerCase() === 'rojo';
        const nameN = o.name.toLowerCase().includes('n');
        const nameA = o.name.toLowerCase().includes('a');

        if(color && (nameA ||nameN))return o
   })
  return ovejas
}
```

**Comment by dalzueta** [comment]
Estas contando ovejas de mas, porq devolves las obejas de color rojo, y aquellas cullo nombre contiene n o que contienen a. Y en realidad deberias contar las de color rojo y cullo nombre contengan las 2 letras a la vez. 

podrias hacer algo asi : 

function contarOvejas(ovejas) {
    ovejas = ovejas.filter(o => o.color.toLowerCase() === 'rojo' && o.name.toLowerCase().includes('n') && o.name.toLowerCase().includes('a'))
  return ovejas
}

**Comment by TeoDiaz** [comment]
> y que además su nombre contenga tanto las letras n Y a

Fijate en estos nombres. 

Noa, tiene la letra N y la letra A, por lo que es valido el nombre
Lucia, tiene la letra A, pero no tiene la letra N, entonces no es un nombre valido. 

Para que sea valido, tiene que tener tanto la N como la A. 

Tu codigo dice: 

`if(color && (nameA ||nameN))return o` - Si tiene color AND si tiene una A OR si tiene una N. 

Echale un vistazo a eso, que casi lo tienes 😉

**Comment by midudev** [comment]
Efectivamente, la lógica no es correcta. Revísala! :)

**Comment by xMichaelRodriguez** [comment]
en efecto estaba mal mi lógica y ya están los primeros 3 retos completados ❤️
