### ISSUE TITLE
day4 - test arbol 2 niveles correctamente - fail

### ISSUE THREAD

**Issue by Joni28492** [midudev/adventjs-issues#77]
no acabo de pasar el test del dia 4, el arbol lo consigo imprimir segun como indica el enunciado pero dice que no esta hecho en 2 niveles, no se si me falta informacion en el eneunciado o soy yo que tengo algun error logico en el codigo
`function createXmasTree(height) {
  // ¡Y no olvides también poner los turrones!

  let arbol = "";
  let extremos = 1;

  //copa del arbol
  for (let i = 0; i < 100; i++) {
    if (i === height) {
      break;
    }
    //rayas anteriores
    for (let j = 0; j < height - i - 1; j++) {
      arbol += "_";
    }
    //hojas
    for (let k = 0; k < extremos; k++) {
      arbol += "*";
    }
    //rayas posteriores
    for (let l = 0; l < height - i - 1; l++) {
      arbol += "_";
    }
    arbol += "\n";
    extremos += 2;
  }

  //tronco
  for (let i = 0; i < 2; i++) {
    for (let j = 0; j < height - 1; j++) {
      arbol += "_";
    }
    arbol += "#";
    for (let k = 0; k < height - 1; k++) {
      arbol += "_";
    }
    arbol += "\n";
  }

  return arbol;
}`

este es mi codigo

**Comment by midudev** [comment]
El árbol no debería terminar con un salto de línea. ¿Has revisado que no termines con un `\n`?
