### ISSUE TITLE
No me devuelve los resultados esperados

### ISSUE THREAD

**Issue by joseenrique-dev** [midudev/adventjs-issues#78]
Hola Midu,  exelente trabajo, Felicidades, m encantó, comencé a probarlo pero no me devuelve los resultados que espero, no sé si sería un error mío, le dejo mi code, saludos cordiales José Enrique.

export default function contarOvejas(ovejas) {
  // aquí tu magia  
  return ovejas.filter(val =>val.color === 'rojo' && containChars(val.name));
}

function containChars(word){
  let status = false;
  word.toLowerCase().split('').map(value=>{
    if(value === 'n' || value === 'a'){
      status = true
    }
  })
  return status
}

**Comment by midudev** [comment]
Estás contando ovejas de más. Estás contando ovejas que sólo tienen la n o la a y debería tener las dos letras.

**Comment by joseenrique-dev** [comment]
Uff q ceguera la mía, ya todo súper que bien, muy motivado por seguir, gracias.

> function containChars(word){
>   return !!word.toLowerCase().includes('a') && word.toLowerCase().includes('n'); 
> }
