### ISSUE TITLE
Problemas con el responsive

### ISSUE THREAD

**Issue by jarrisondev** [midudev/adventjs-issues#8]
No se si es que en principio no tiene responsive, pero creo que sería necesario tenerlo. ví la publicación desde el móvil y al abrir pensé que era problema de mi celular jajaja.

**Comment by jarrisondev** [comment]
![imagen](https://user-images.githubusercontent.com/62910118/144291085-163fdc82-e902-4dba-bd33-7ae45ec4623c.png)
![imagen](https://user-images.githubusercontent.com/62910118/144291135-849edd54-5b58-4130-b155-f382e78e757d.png)

**Comment by midudev** [comment]
Duplicada
