### ISSUE TITLE
Margen superior del contenedor dentro del header

### ISSUE THREAD

**Issue by guzmanpdro** [midudev/adventjs-issues#80]
En versión móvil hasta tablets, se podría eliminar el margin-top del container dentro del header?

**Comment by midudev** [comment]
Hecho!

<img width="484" alt="CleanShot 2021-12-06 at 12 11 03@2x" src="https://user-images.githubusercontent.com/1561955/144836229-d499896a-3f01-4709-aa1c-7908783119d4.png">
