### ISSUE TITLE
Horario publicación eventos

### ISSUE THREAD

**Issue by ArkoxHub** [midudev/adventjs-issues#81]
Hola,
Los ejercicios podrían salir a las 0:00 horario de España? 
Gracias.
Un abrazo y gracias por esta iniciativa tan bonita y útil

**Comment by midudev** [comment]
😆  Ojalá yo fuese el primero en saber cuándo van a salir los retos. Al menos, voy a intentar que sea el día seguro...

También quiero poner algún tipo de push notifications para que quien quiere, se suscriba.

**Comment by ArkoxHub** [comment]
> 😆  Ojalá yo fuese el primero en saber cuándo van a salir los retos. Al menos, voy a intentar que sea el día seguro...
> 
> 
> 
> También quiero poner algún tipo de push notifications para que quien quiere, se suscriba.

Muchas gracias Midu, eso estaría genial también 🥳💙

**Comment by midudev** [comment]
Vamos a implementar Web Push Notifications: https://github.com/midudev/adventjs-issues/issues/115
