### ISSUE TITLE
Error de validación en reto #2

### ISSUE THREAD

**Issue by DagonGH** [midudev/adventjs-issues#83]
Hola para resolver el problema planteado en el reto numero dos, he escrito el siguiente código:

```javascript
export default function listGifts(letter) {
 let regalos = letter.split(/\s+/).map(s => s.trim()).filter(r => !r.startsWith('_'))
 return regalos.reduce(function (regalo, i) {
     !regalo[i] ? regalo[i] = 1 : regalo[i]++
     return regalo
  }, {})  
}
```

Sin embargo obtengo el siguiente error "Me parece que no has tenido en cuenta los espacios dobles en blanco...trim trim trim!", sin embargo esta afirmación no es correcta, dado que hice diferentes pruebas con la cadena: 

```javascript
const carta = 'bici coche    balón _playstation bici   coche peluche   bici
```

y funciona correctamente. Alguna sugerencia, de verdad es un error mío o es un error de validación?

**Comment by midudev** [comment]
Con el input:

```
const carta = "bici coche     balón _playstation bici coche peluche  ";
```

Tu código devuelve:

```
{
  bici: 2,
  coche: 2,
  'balón': 1,
  peluche: 1,
  '': 1
}
```

¿Quieren los niños un string vacío? No lo creo. :P

**Comment by davorpa** [comment]
prueba con 

```js
const carta = "   bici coche    balón _playstation bici   coche peluche   bici   "
```

split no elimina espacios al inicio o final ni cadenas vacias

**Comment by DagonGH** [comment]
Oh! Lo siento, creo que no evalué ese escenario. Muchas gracias.
