### ISSUE TITLE
Problema en la tarea numero dos

### ISSUE THREAD

**Issue by fabrizhioa** [midudev/adventjs-issues#84]
/*
    letter = letter.split(/\s+/);
    let regalos = {};
    console.log(letter);
    letter.map((r) => {
        if (r.includes('_') === false) {
            regalos[r] = regalos[r] == null ? 1 : regalos[r] + 1;
        }
    });
    return regalos;
*/

este es el codigo que utilizo para resolver la actividad 2 pero el sistema me marca que no estoy teniendo en cuenta los espacios dobles cuando en mi split si estoy solicitando que si es uno o mas espacios no se cuenten

**Comment by AroliSG** [comment]
export default function listGifts(letter) {
  let obj = {};
  let loop = letter
    .split (' ')
 

    loop.forEach ((e, index) => {
      if (!e) return;
      if (e.includes ('_')) return;
      if (obj [e]) obj [e] +=  1;
      else obj [e] = 1;

      console.log (e)
    }); 
 
  // ¡Tú puedes!
  return obj;
}

**Comment by Dave-JunDev** [comment]
te faltaba poner un trim, cuando llamas letter por primera vez 

export default function listGifts(letter) {
 letter = letter.trim().split(/\s+/);
let regalos = {};
console.log(letter);
letter.map((r) => {
if (r.includes('_') === false) {
regalos[r] = regalos[r] == null ? 1 : regalos[r] + 1;
}
});
  return regalos
}
