### ISSUE TITLE
No acepta los resultados y el codigo es correcto

### ISSUE THREAD

**Issue by menendezluis** [midudev/adventjs-issues#85]
Hola, se que tienes muchas actividades en que ocuparte, el desafió me parece genial pero voy flipado que no me acepta mis respuestas y en output se ven correctas, aun no intento el numero 5 pero de todas formas muchas gracias.

ejercicio #6 
https://jsfiddle.net/lmenendez/zoy5hkbv/
ejercicio #4
https://jsfiddle.net/lmenendez/7yjLuqok/4/

**Comment by ghost** [comment]
No es correcto, en el jsfiddle #6 debería devolver [1, 5] y no [3, 3], solo existe un 3, en cuanto al #4, creo que te sobra un retorno de carro(\n). Animo!!!.

Para el #6 usa el siguiente pseudo test y lo verás:
```js
const tests = [
      [[0, 2, 2, 3, -1, 1, 5], 6, [1, 5]],
      [[0, 0, 1, 2, 5, 8, 3], 9, [1, 8]],
      [[1, 1, 2, 0, 8, 6, 8], -1, null],
      [[0, 0, 1, 2, 5, 8, 5], 0, [0, 0]],
      [[3, 0, 1, 2, 5, 8, 9], 5, [3, 2]],
      [[3, -4, -1, 0, 6, -5], -6, [-1,-5]]
    ];

tests.forEach(([paramA, paramB, expected]) => {
  const strResult = JSON.stringify(sumPairs(paramA, paramB));
  const strExpected = JSON.stringify(expected);
  console.log(strResult === strExpected ? ' correcto' : ` incorrecto, devuelve ${strResult} y debe devolver ${strExpected}`)
});
```

**Comment by midudev** [comment]
@menendezluis El árbol de navidad termina con un salto de línea innecesario y el otro tampoco parece correcto... Revísalo!
