### ISSUE TITLE
Parar automáticamente bucles infinitos

### ISSUE THREAD

**Issue by Cedgo1997** [midudev/adventjs-issues#86]
En ocasiones al construir un bucle, si este no tiene una cota, se cuelga la página. Estaría genial que se pudiese detectar eso y detener el posible bucle infinito para que eso no suceda. Además que como no guarda el progreso del código, al colgarse la página, todo el código se pierde.

**Comment by davorpa** [comment]
La verdad creo que se solucionaría junto con otras issues como el consumo de memoria tras muchas ejecuciones si
- los test/compilación no se ejecutaran automáticamente
- o más flexible: ampliar el timeout para su ejecución o permitiendo al usuario configurarlo a gusto (guardar config en el localstorage?)

**Comment by midudev** [comment]
Hemos añadido esto a la nueva versión de AdventJS:
https://adventjs.dev/
