### ISSUE TITLE
Reto #6 SumaPairs

### ISSUE THREAD

**Issue by mtofani** [midudev/adventjs-issues#87]
Midu,chicos! ejecuté las pruebas del 6 y obtengo los mismos output pero no paso el test de validación. Me quede sin ideas : D pegan un vistazo? Gracias

<img width="382" alt="captura" src="https://user-images.githubusercontent.com/69044164/144964943-dc69f3fb-0419-4afc-a4a9-ed04072aed54.png">

const findNumber = (numbers, result) => {
    bool = false;

    for (let i = 0; i < numbers.length; i++) {
        var subArray = numbers.slice(i + 1);

        for (let j = 0; j < subArray.length; j++) {
            par1 = numbers[i];
            par2 = subArray[j];

            if (parseInt(par1) + parseInt(par2) === result) {
            bool = true;
            return [par1, par2];
            }
        }
        if (!bool) return null;
    }
};
let a = findNumber([3, 5, 7, 2], 10);
console.log(a);

**Comment by dalzueta** [comment]
corriendolo localmente y ejecutando las mismas pruebas, me fallaba solo una, lo solucione sacando ese if(!bool) ... fuera del for. 
En la plataforma tiraba error por la forma en declarar las variables.  
![image](https://user-images.githubusercontent.com/38339227/145033623-886b32bc-c1d9-4214-ae64-b08efd2467d5.png)

**Comment by mtofani** [comment]
Gracias @dalzueta , evidentemente en la madrugrada no me di cuenta que quedo dentro, y lo de las variables (muy tricky).
Saludo!!
