### ISSUE TITLE
Me gustaria poder ver el ultimo mensaje mostrado.

### ISSUE THREAD

**Issue by meolivares06** [midudev/adventjs-issues#88]
Al detectar los cambios automaticamente se corren los test y se dan mensajes muy utiles.
Pero estos mensajes al cabo de un tiempo corto desaparecen.
Me gustaria poder ver el ultimo puesto que es informacion util para ir razonando.

Podria mostrarse el mensaje y no quitarlo o permitir correr los test manualmente para ver el mensaje a demanda.

**Comment by itsjuancho** [comment]
Ídem. Venía a abrir la misma sugerencia. Desaparecen relativamente rápido y vuelve al mensaje de "modifica algo para ejecutar automáticamente los test". Sería chévere si pudiese haber un espacio donde se registren los mensajes de los test, con fecha y hora como para poderlos diferenciar.

**Comment by midudev** [comment]
Hemos añadido esto a la última versión de AdventJS:
https://adventjs.dev/
