### ISSUE TITLE
verificación reto 7 

### ISSUE THREAD

**Issue by Dave-JunDev** [midudev/adventjs-issues#89]
al subir el reto me sale el siguiente error:
![image](https://user-images.githubusercontent.com/74385834/145089918-73a5c9f0-b410-401a-9c34-2c065242fb54.png)

pero no se como puedo ingresar y verificar la cantidad de almacenes profundos para realizar la verificación de los datos, este código funciona con los ejemplos pero si llegara ser, con un nivel mas como el ejemplo a continuación: 

![image](https://user-images.githubusercontent.com/74385834/145090450-21b6960b-5e34-4859-9bba-5d06ebbbd816.png)

Codigo funcional con los ejemplos:
function contains(store, product) {
    var result = "";

    for (var i in store)
    {
        let data = Object.values(store[i])

        for (var n in data)
        {

            let reduc = Object.values(data[n])

            for (var j = 0; j < reduc.length; j++)
            {
               if (reduc[j] === product)
               {
                  result = reduc[j]
               }

            }
        }

    }
    var exit = result.length != 0 ?  true :  false;
    return exit
}

**Comment by dalzueta** [comment]
Buen dia, al parecer si le agregas un nivel mas, no encuentra el producto. Aqui agregue un nivel mas al almacen, y tu codigo no encontro el producto. Quizas a eso hace referencia el mensaje 
![image](https://user-images.githubusercontent.com/38339227/145095529-5cdee736-8891-4f88-a4da-0e73946b163d.png)

**Comment by Dave-JunDev** [comment]
@dalzueta lo se, pero mi pregunta es como hago para identificar esa cajón de más

**Comment by dalzueta** [comment]
Usando recursion lo podes resolver, de esa forma no va a importar el nivel de profundidad donde este el producto q se busca. 
aqui un diagrama echo a las apuradas, espero te sirva 
![image](https://user-images.githubusercontent.com/38339227/145098809-3a9a747b-d4ec-42b7-bff3-9ff79abc462a.png)

**Comment by Dave-JunDev** [comment]
@dalzueta realce el codigo similiar al diagrama pero aun asi no me funciona me dice que me falta encontrar una camisa 

const almacen = {
    'estanteria1': {
      'cajon1': {
        'producto1': 'coca-cola',
        'producto2': 'fanta',
        'producto3': 'sprite'
      }
    },
    'estanteria2': {
      'cajon1': 'vacio',
      'cajon2': {
        'producto1': 'pantalones',
        'producto2': 'camiseta' // <- ¡Está aquí!
      }
    }
  }



function contains(store, product)
    {
        var vacio = Object.values(store)

        if (vacio.length === 0 )
        {
          return console.log("No puede dejar campos vacios")
        }
        else
        {
          var keys = Object.keys(store)
          for (let i = 0; i < keys.length; i++)
          {
            var exit = search (store[keys[i]], product) ? true :  false;
          }
          return console.log(exit)
        }

    }


    function search(data, product)
    {
        var result;

        for (let n in data)
        {
            let reduc = Object.values(data[n])
                for (var j = 0; j < reduc.length; j++)
                {
                    if (reduc[j] === product)
                    {
                       result = reduc[j]
                    }
                }
        }
        return result
    }

    contains(almacen, 'camiseta')

**Comment by dalzueta** [comment]
quizas no hice del todo bien el diagrama. Espero explicarme mejor asi . 
Lo primero q hago es ver si lo que recibo es un objeto o no, porq si no lo es debo ver si el valor de este campo es el q busco (la camiseta u otro objeto). Pero si es un objeto , significa q dentro tiene mas campos q pueden ser otros objetos y debo recorrerlos , entonces hago la llamada a esta misma funcion por cada uno de los campos . 
Disculpa si no me explico bien
![image](https://user-images.githubusercontent.com/38339227/145117501-8ced0133-70c7-48f8-a372-074228d9ffee.png)

**Comment by midudev** [comment]
Cierro la issue porque no es un problema pero del test.

**Comment by davorpa** [comment]
Hay varias formas de comprobar si una variable es un objeto plano o de un tipo determinado.

`Object.values` falla para `null` y `undefined` lanzado un Error y con strings retorna sus caracteres.

- Object type string: `Object.prototype.toString.call(x) === ...`
- typeof operator: `typeof x === ...`
- type wrap: `Object(x) === ...`
- constructor equality: `x.constructor === ...`

Aquí una matrix para ver que sucede con todos los tipos:
```js
for(const x of [
      void 0, null,
      4, .5, Number(6), new Number(8),
      5n, BigInt(7), BigInt("9"),
      "#", String("a"), new String, new String("b"),
      true, Boolean(true), new Boolean,
      function(){}, x => x, new Function,
      /aa/g, RegExp(), new RegExp, 
      {1:2}, new Object, new Object(4), Object.create(null),
      [6], Array(), Array(3), Array([5]), new Array, new Array([2]), new Array(3),
      new Set("ab"),
      new Map([["a", 1]]), new Map([["a", 1]]).values(),
      new WeakMap(), new WeakSet(),
    ])
  console.log(x,
              typeof x, 
              {}.toString.call(x),
              x === Object(x),
              !!x && x.constructor === Object,
              // generic getvalues copy using iterator (for Set, Map...)
              x && (typeof x.values === "function" ? Array.from(x.values()) : Object.values(x))
             );
```
