### ISSUE TITLE
El editor se queda cargando en safari

### ISSUE THREAD

**Issue by luisbar180492** [midudev/adventjs-issues#90]
<img width="1574" alt="image" src="https://user-images.githubusercontent.com/11236113/145104463-4a4554f3-d784-4ea9-bf52-d69042d0ea5d.png">

**Comment by midudev** [comment]
¿Qué versión de Safari es? He estado probando en un par de sistemas macOS y no he podido replicarlo.

¿Puedes abrir la consola para ver si hay algún error?

**Comment by luisbar180492** [comment]
Lo siento por la demora en responder, aquí tenes los datos que me pediste

Version de Safari: Version 14.1.1 (16611.2.7.1.4)
Y lo siguiente se ve en la consola
<img width="501" alt="image" src="https://user-images.githubusercontent.com/11236113/145267683-b899c11e-d15d-4ee3-99b9-5449ebec65d8.png">

Si necesitas algo mas me decís por favor, y gracias por tu gran aporte

**Comment by midudev** [comment]
¿Te pasa en cualquier reto? ¿O es un reto en concreto? He probado con Safari 14.1.1 en otro ordena y no tengo forma de replicarlo. :(

**Comment by luisbar180492** [comment]
Probe con 5 retos y pasa lo mismo, si te parece, me podes compartir el repo de adventjs para correrlo local y así te hecho una mano con eso :)
