### ISSUE TITLE
Reto #2

### ISSUE THREAD

**Issue by nvegaBIRT** [midudev/adventjs-issues#92]
Hola! ¿Puede que haya un error? Estoy controlando que haya más de un espacio con regExp  /\s+/. He ejecutado el código con node y se ejecuta sin fallos pero el test de adventjs me lanza el siguiente error "Me parece que no has tenido en cuenta los espacios dobles en blanco...trim trim trim!"
Mi código:
export default function listGifts(letter) {
  // ¡Tú puedes!
  const espacios = /\s+/;
  const sinTachar = (o) => (/^[_]/.test(o))==false;
  let arrRegalos = letter.split(espacios);
  arrRegalos = arrRegalos.filter(sinTachar)
    
  return arrRegalos.reduce((a,d) => (a[d] ? a[d]+=1 : a[d] = 1, a), {}); 
}

//output node.js 
// { bici: 2, coche: 2, 'balón': 1, peluche: 1 }

**Comment by davorpa** [comment]
Prueba con 

```js
const carta = "   bici coche    balón _playstation bici   coche peluche   bici   ";
```

`split` no elimina espacios al inicio o final ni cadenas vacías

En todo caso, no es un bug o feature del portal. Se recomienda usar el canal de Discord de la comunidad para este tipo de dudas: https://discord.com/channels/741237973663612969/915910832259477534
