### ISSUE TITLE
FeedBack Code

### ISSUE THREAD

**Issue by fabCastillo** [midudev/adventjs-issues#96]
_**Hola a todos!**_

**Queria dar gracias por estas actividades primero que todo, pero también, me gustaria darte como una sugeria sobre tener un apartado de la gente que participo en cada reto, una sección de como los demás lograron el reto, esto es una forma de FeedBack para que los que tengamos menos experiencia en crear algoritmos, o los que nos hacemos todo un envuelto para llegar a la misma solución, sepamos como administrar bien nuestras ideas con las mejores soluciones de la comunidad!**

**Comment by davorpa** [comment]
Relacionado con #10

**Comment by GomezJuanEfe** [comment]
Hola, aquí en GitHub hay muchos repositorios de personas que han subido sus respuestas. A mi me ha servido para exactamente lo que tu dices, apenas estoy empezando y necesito ver cómo los demás, la gente con más experiencia, se acerca al código.
