### ISSUE TITLE
Responsive desacoplado

### ISSUE THREAD

**Issue by itsjuancho** [midudev/adventjs-issues#97]
Desde esta mañana noto que el diseño se ve como muy pegado a los bordes, tanto en la pantalla de mi computador como en mi teléfono. Lo raro es que si se redimensiona la ventana, a una resolución más pequeña, se acomoda. Es como si se le hubiera hecho reset a las márgenes.

En ordenador: https://user-images.githubusercontent.com/72939711/145255259-6c8a000a-0062-4d82-9e7e-c8c90a6ef259.png
En móvil: https://user-images.githubusercontent.com/72939711/145255522-127adb0f-3ef2-4db8-b0a8-bc447049fd83.png
Con la ventana redimensionada: https://user-images.githubusercontent.com/72939711/145255668-121af857-b1bf-4ebd-b21c-a161d46c1f8c.png

**Comment by davorpa** [comment]
Creo que es a raíz de resolver #80.

La verdad es que en el móvil molesta algo porque no tienes zona lateral dónde poder hacer scroll si algun panel (intelligence / context / commands) esta visible.

**Comment by midudev** [comment]
Creo que esto ya está arreglado.

<img width="411" alt="Captura de pantalla 2021-12-10 a las 0 27 52" src="https://user-images.githubusercontent.com/1561955/145491662-09c8cf9c-c08c-4d3c-91ef-0dd7f37b6af2.png">
