### ISSUE TITLE
Challenge #8: Un console.log por ahí

### ISSUE THREAD

**Issue by tomimelo** [midudev/adventjs-issues#98]
En el challenge 8 se te ha quedado algun console.log
Al momento de testear el código sale en consola el return de la función y el resultado esperado.

![image](https://user-images.githubusercontent.com/60193559/145276646-549ea704-a21b-4a0c-9930-74ce41a1bba7.png)

**Comment by tomimelo** [comment]
He visto que también sucede en otros retos. No se si es a propósito, por las dudas lo comento.

**Comment by midudev** [comment]
Creo que ya debería estar arreglado. :)
