### ISSUE TITLE
Se suma el total de usuarios que completó el reto cada vez que se envía la solución

### ISSUE THREAD

**Issue by tomimelo** [midudev/adventjs-issues#99]
Aunque ya tenga la solución del reto enviada, si hago algún cambio en el código y lo vuelvo a enviar se suma 1 al total de usuarios que completaron el reto. Si se refresca la página el número vuelve a mostrarse correctamente. Quizás sería bueno revisar si ya haz completado el reto en vez de sumar +1 cada vez que se presiona el botón.

![advent-issue](https://user-images.githubusercontent.com/60193559/145277574-019707d2-97cf-4d18-9c60-6ce693e96a1f.gif)

**Comment by midudev** [comment]
Jajaja sí. Eso es porque estoy usando una UI optimista. 😆 

He preferido dejar esto porque poca gente iba a estar enviando la solución todo el rato... y en realidad esto no llega a la BBDD.

**Comment by midudev** [comment]
Arreglado! :)
